In [ ]:
print("Assalam o Alaikum!\nAll the required charts and visuals are included in this colab file.\nSome of the code was just used for inspection purpose and it is mentioned")
print("as Non functional code in the start of that block using comments. Also, we are using a dynamic slider to set years for data visualization. If you want to show data")
print("for any specific year or yearss, just select years from the slider and re-execute the chart or KPI code to get updated results, Thank you!\n")

Assalam o Alaikum!
All the required charts and visuals are included in this colab file.
Some of the code was just used for inspection purpose and it is mentioned
as Non functional code in the start of that block using comments. Also, we are using a dynamic slider to set years for data visualization. If you want to show data
for any specific year or yearss, just select years from the slider and re-execute the chart or KPI code to get updated results, Thank you!

In [ ]:
import pandas as pd
import gdown
import os
import glob

# 1. PASTE YOUR MAIN DIRECTORY (FOLDER) LINK HERE
folder_url = "https://drive.google.com/drive/folders/1ZbSqVHSnKTot7e0L5fiN2U7n7TfAk_wF?usp=drive_link"

# 2. Download the folder
# This downloads the folder and its contents to the Colab runtime
output_directory = "Project_Data" # We will save files in this folder name
gdown.download_folder(folder_url, output=output_directory, quiet=False, use_cookies=False)

# 3. Load the files into a dictionary
dataframes = {}

# Get all xlsx files in the directory
file_paths = glob.glob(f"{output_directory}/*.xlsx")

print("\n--- Loading Files ---")
for path in file_paths:
    # Extract filename without extension for the key (e.g., 'Annual')
    file_name = os.path.basename(path).replace('.xlsx', '')

    try:
        dataframes[file_name] = pd.read_excel(path)
        print(f"Loaded: {file_name} | Shape: {dataframes[file_name].shape}")
    except Exception as e:
        print(f"Error loading {file_name}: {e}")

# Access examples:
# df_annual = dataframes['Annual']

Retrieving folder contents

Processing file 13Czr8DyUV4SH1bPLEN-xmr1pVcXFCZwU Annual.xlsx
Processing file 1lHM8zBNAorCgahGosXaBD_k5KjhLsrbE Economy.xlsx
Processing file 1vg9z8LhbldgcHgsEm-X-Gjcf9nlE6g-F Education.xlsx
Processing file 11qhINOB4bLGFy7MBlB1wHWpsOi9Rsgkn Employment.xlsx
Processing file 1y7m4NhnVu3M9xEyVvbbQtwgcnE8eWC6j Health.xlsx
Processing file 1n3UbsXeDoRdpTAeowMBrXbrHgMoGp4v6 Household.xlsx

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=13Czr8DyUV4SH1bPLEN-xmr1pVcXFCZwU
To: /content/Project_Data/Annual.xlsx
100%|██████████| 10.3k/10.3k [00:00<00:00, 22.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1lHM8zBNAorCgahGosXaBD_k5KjhLsrbE
To: /content/Project_Data/Economy.xlsx
100%|██████████| 9.70k/9.70k [00:00<00:00, 21.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1vg9z8LhbldgcHgsEm-X-Gjcf9nlE6g-F
To: /content/Project_Data/Education.xlsx
100%|██████████| 12.7k/12.7k [00:00<00:00, 26.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=11qhINOB4bLGFy7MBlB1wHWpsOi9Rsgkn
To: /content/Project_Data/Employment.xlsx
100%|██████████| 10.4k/10.4k [00:00<00:00, 20.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1y7m4NhnVu3M9xEyVvbbQtwgcnE8eWC6j
To: /content/Project_Data/Health.xlsx
100%|██████████| 12.3k/12.3k [00:00<00:00, 12.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1n3UbsXeDoRdpTAeowMBrXbrHgMoGp4v6
To: /content/Project_Data/Household.xlsx
100%|██████████| 17.7k/17.7k [00:00<00:00, 27.3MB/s]

--- Loading Files ---
Loaded: Health | Shape: (51, 14)
Loaded: Annual | Shape: (20, 10)
Loaded: Household | Shape: (61, 28)
Loaded: Economy | Shape: (27, 5)
Loaded: Education | Shape: (51, 14)
Loaded: Employment | Shape: (28, 8)

Download completed

In [ ]:
#Page 01 - AVG Income

# 1. Select the Economy dataframe
# We use .copy() to ensure we don't modify the original dataframe stored in the dictionary
df_economy = dataframes['Economy'].copy()

# 2. Define the column name
# Based on your previous error message, this is the correct column name
income_col = 'Avg Income per HouseHold'

# 3. Clean the Income Column
# We convert the column to numeric. 'errors=coerce' is crucial here because
# it turns any text values (like the repeated "Year Region..." headers) into NaN.
df_economy[income_col] = pd.to_numeric(df_economy[income_col], errors='coerce')

# 4. Calculate the Average
# We calculate the mean of the entire column.
# Pandas automatically ignores the NaN values we created in the cleaning step.
avg_national_income = df_economy[income_col].mean()

# 5. Display the result
print(f"Average National Income (All Rows): {avg_national_income:,.2f}")

Average National Income (All Rows): 23,087.56

In [ ]:
#Page 01 - Graph

import plotly.graph_objects as go
import pandas as pd

# --- DATA PREPARATION (Same as before) ---
df_edu = dataframes['Education'].copy()

# Fix Headers
df_edu.rename(columns={
    'LITERACY RATES (10 YRS AND OLDER)': 'Lit_Rate_M',
    'Unnamed: 9': 'Lit_Rate_F'
}, inplace=True)

# Remove sub-header row and filter for OVERALL
df_edu_clean = df_edu.iloc[1:].copy()
df_edu_national = df_edu_clean[df_edu_clean['Region'].astype(str).str.strip() == 'OVERALL'].copy()

# Convert columns to numeric
cols_to_fix = ['Lit_Rate_M', 'Lit_Rate_F']
for col in cols_to_fix:
    df_edu_national[col] = pd.to_numeric(df_edu_national[col], errors='coerce')

# Calculate GPI
df_edu_national['GPI'] = df_edu_national['Lit_Rate_F'] / df_edu_national['Lit_Rate_M']

# Create Sort Year
df_edu_national['Sort Year'] = df_edu_national['Year'].astype(str).str[:4].astype(int)
df_plot = df_edu_national.sort_values(by='Sort Year')

# --- PLOTLY INTERACTIVE VISUALIZATION ---

# Create the figure
fig = go.Figure()

# Add the Area Trace
fig.add_trace(go.Scatter(
    x=df_plot['Sort Year'],
    y=df_plot['GPI'],
    mode='lines+markers', # Show both line and dots
    fill='tozeroy',       # Fill area to the x-axis (Area chart behavior)
    name='GPI',
    line=dict(color='#E87A46', width=3), # Match the orange color
    marker=dict(size=8),
    hovertemplate='<b>Year</b>: %{x}<br><b>GPI</b>: %{y:.2f}<extra></extra>' # Custom tooltip
))

# Update Layout to match Power BI style
fig.update_layout(
    title=dict(text='<b>LITERACY GENDER PARITY TREND (GPI)</b>', font=dict(size=18)),
    xaxis=dict(
        title='Year',
        tickmode='linear', # Force it to show all years if space permits
        tickangle=-45
    ),
    yaxis=dict(
        title='GPI',
        range=[0.4, 0.7], # Set fixed range to match your view
        gridcolor='lightgrey'
    ),
    plot_bgcolor='white', # Clean white background
    hovermode="x unified" # Shows a vertical line guide when hovering (like Power BI)
)

# Show the interactive plot
fig.show()

# Optional: Code to save this as an HTML file for hosting later
# fig.write_html("literacy_gpi_interactive.html")

In [ ]:
#Page 2
#Master Slicer for year range selection

import ipywidgets as widgets
from IPython.display import display
import pandas as pd

# --- 1. Create the Master List of Years ---
# We iterate through all loaded dataframes to find every unique year string available.
all_year_ranges = set()
print("Scanning files for 'Year' data...")
for name, df in dataframes.items():
    if 'Year' in df.columns:
        # Convert to string, strip whitespace, drop NaNs, get unique values
        years = df['Year'].dropna().astype(str).str.strip().unique().tolist()
        all_year_ranges.update(years)
        print(f" - Found {len(years)} unique years in {name}.xlsx")

# Sort the years alphabetically for the dropdown list
sorted_years_options = sorted(list(all_year_ranges))

# --- 2. Create the Multi-Select Widget ---
# This widget replicates the Power BI slicer shown in your screenshots
# It allows selecting multiple options (e.g., holding Ctrl/Shift or just clicking on mobile).
year_slicer_widget = widgets.SelectMultiple(
    options=sorted_years_options,
    # Default selection: let's pick the last 2 available years as a starting point
    value=sorted_years_options[-2:] if len(sorted_years_options) >= 2 else sorted_years_options,
    rows=10, # How many rows to show at once in the box
    description='Year Range:',
    disabled=False,
    layout=widgets.Layout(width='300px')
)

print("\n--- Master Year Slicer Created ---")
print("Select year ranges below. These selections will be passed as variables to your future KPIs.")
display(year_slicer_widget)

Scanning files for 'Year' data...
 - Found 10 unique years in Health.xlsx
 - Found 19 unique years in Annual.xlsx
 - Found 10 unique years in Household.xlsx
 - Found 11 unique years in Economy.xlsx
 - Found 10 unique years in Education.xlsx
 - Found 11 unique years in Employment.xlsx

--- Master Year Slicer Created ---
Select year ranges below. These selections will be passed as variables to your future KPIs.

SelectMultiple(description='Year Range:', index=(34, 35), layout=Layout(width='300px'), options=('1998-1999', …

In [ ]:
# helper function for year selection
# --- STANDARD HELPER FUNCTION ---
def filter_by_selected_years(df, selected_years_variable, year_col_name='Year'):
    """
    Global helper function to filter any dataframe based on the
    variable passed from the UI slicer.
    """
    # 1. Create a copy to avoid SettingWithCopy warnings
    df_filtered = df.copy()

    # 2. Ensure the dataframe's year column is clean string format for comparison
    df_filtered['temp_year_str'] = df_filtered[year_col_name].astype(str).str.strip()

    # 3. Filter: Keep rows where the year matches one of the selected variables
    # The 'selected_years_variable' is a tuple of strings, e.g., ('2018-2019', '2019-2020')
    df_final = df_filtered[df_filtered['temp_year_str'].isin(selected_years_variable)]

    # Clean up temp column
    df_final = df_final.drop(columns=['temp_year_str'])

    return df_final


# --- EXAMPLE: FUTURE KPI STRUCTURE ---
# This is a template for how you will write your future KPIs.
# Notice it accepts 'selected_years_tuple' as an argument.

def calculate_example_kpi(df, selected_years_tuple):
    # 1. Apply the standard filter using the passed variable
    filtered_df = filter_by_selected_years(df, selected_years_tuple)

    # 2. Perform calculation (e.g., count rows for this example)
    kpi_result = len(filtered_df)

    print(f"--- Calculating KPI for selected years: {selected_years_tuple} ---")
    print(f"Dataframe rows after filtering: {kpi_result}")
    # return kpi_result

# --- CONNECTING IT UP (DEMONSTRATION) ---
# We use widgets.interactive_output to automatically run a function
# whenever the 'year_slicer_widget' changes.

def update_dashboard_demo(selected_years):
    # This function automatically receives the new variable whenever you click the slicer.
    # You can pass this variable to any number of KPI functions here.

    # Example using the Economy data (assuming it exists)
    if 'Economy' in dataframes:
        calculate_example_kpi(dataframes['Economy'], selected_years)
    else:
        print(f"Selected variables: {selected_years}. (Economy data not found for demo).")

# Link the widget to the demo function
out = widgets.interactive_output(update_dashboard_demo, {'selected_years': year_slicer_widget})

# Display the output area (go back up and change the slicer selection to see this update!)
display(out)

Output()

In [ ]:
# Inspection code - Not functional
# Inspect just the Adult Literacy columns
df_edu = dataframes['Education']
print("--- Columns 11 to 14 (Adult Literacy Section) ---")
print(df_edu.iloc[0:5, 11:14])

--- Columns 11 to 14 (Adult Literacy Section) ---
  Adult Literacy Rate Unnamed: 12 Unnamed: 13
0                   M           F           T
1                  58          28          43
2                  57          30          43
3                  64          32          49
4                  54          15          34

In [ ]:
# @title
# Page 02 - Adult literacy rate % - function embedded in single function below also
# --- KPI DEFINITION: National Adult Literacy Rate ---
def calculate_national_adult_literacy(df_education, selected_years_tuple):
    """
    Calculates the Average National Adult Literacy Rate for the selected years.
    Logic: Average of 'Adult Literacy Rate - Total' where Region is 'OVERALL'.
    """

    # 1. Create a working copy of the dataframe
    df = df_education.copy()

    # 2. Rename the specific column we need (Unnamed: 13 -> Adult_Lit_Total)
    # Based on your verification: 'Unnamed: 13' is the Total (T) column
    df.rename(columns={'Unnamed: 13': 'Adult_Lit_Total'}, inplace=True)

    # 3. Filter for National Level data (Region = "OVERALL")
    # We strip whitespace to be safe (' OVERALL ' -> 'OVERALL')
    df_national = df[df['Region'].astype(str).str.strip() == 'OVERALL'].copy()

    # 4. Clean the Data: Convert column to numeric
    # 'errors=coerce' turns text headers (like 'T') into NaN so they don't crash the math
    df_national['Adult_Lit_Total'] = pd.to_numeric(df_national['Adult_Lit_Total'], errors='coerce')

    # 5. Apply the Dynamic Year Filter
    # We use the helper function you created in the previous step
    df_filtered = filter_by_selected_years(df_national, selected_years_tuple, year_col_name='Year')

    # 6. Calculate the KPI
    # Power BI Logic: AVERAGE(Education[Adult Literacy Rate - T])
    # The mean() function ignores NaNs automatically
    kpi_value = df_filtered['Adult_Lit_Total'].mean()

    # 7. Display the Result
    # If no data is found for the selected years, handle it gracefully
    if pd.isna(kpi_value):
        print(f"National Adult Literacy Rate: No Data for {selected_years_tuple}")
    else:
        print(f"National Adult Literacy Rate: {kpi_value:.2f}%")

    return kpi_value

# --- LINKING TO SLICER ---
# This updates the 'update_dashboard_demo' function to include this new KPI.
def update_dashboard(selected_years):
    print(f"--- DASHBOARD UPDATE (Selected Range: {selected_years}) ---")

    # Check if file is loaded
    if 'Education' in dataframes:
        calculate_national_adult_literacy(dataframes['Education'], selected_years)
    else:
        print("Error: 'Education.xlsx' not loaded.")

# Re-display the interactive output with the new KPI
output_display = widgets.interactive_output(update_dashboard, {'selected_years': year_slicer_widget})
display(output_display)

Output()

In [ ]:
# @title
# Inspection code - non functional
# 1. Load Health Data
df_health = dataframes['Health']

# 2. Inspect the Header Rows (Rows 0-4)
# We look for "FULL IMMUNISATION" in the top row and "T" in the second row
print("--- First 5 Rows of Health Data ---")
print(df_health.head())

# 3. Check the Region Names
print("\n--- Unique Regions ---")
print(df_health['Region'].dropna().unique())

# 4. Print all columns to help us count the index
print("\n--- Column List ---")
print(list(enumerate(df_health.columns)))

--- First 5 Rows of Health Data ---
        Year   Region TETANUS TOXOID(% MARRIED WOMEN AGED 15-49)  Unnamed: 3  \
0        NaN      NaN                                           U          R
1  1998-1999  OVERALL                                          66         31
2  1998-1999   Punjab                                          65         38
3  1998-1999    Sindh                                          72         23
4  1998-1999     NWFP                                          54         26

  Unnamed: 4 AT LEAST 1 IMMUNISATION (12-23 MONTHS) Unnamed: 6 Unnamed: 7  \
0          T                                      M          F          T
1         39                                     75         70         73
2         45                                     83         80         81
3         40                                     65         52         58
4         29                                     71         69         70

  FULL IMMUNISATION (12-23 MONTHS BASED ON RECALL AND RECORD) Unnamed: 9  \
0                                                  M                   F
1                                                 52                  47
2                                                 57                  52
3                                                 42                  35
4                                                 52                  56

  Unnamed: 10 DIARRHOEA LAST 30 DAYS(UNDER 5 YEARS) Unnamed: 12 Unnamed: 13
0           T                                     M           F           T
1          49                                    14          14          14
2          55                                    14          15          15
3          38                                    11          11          11
4          54                                    18          16          17

--- Unique Regions ---
['OVERALL' 'Punjab' 'Sindh' 'NWFP' 'Balochistan' 'KPK']

--- Column List ---
[(0, 'Year'), (1, 'Region'), (2, 'TETANUS TOXOID(% MARRIED WOMEN AGED 15-49) '), (3, 'Unnamed: 3'), (4, 'Unnamed: 4'), (5, 'AT LEAST 1 IMMUNISATION (12-23 MONTHS)'), (6, 'Unnamed: 6'), (7, 'Unnamed: 7'), (8, 'FULL IMMUNISATION (12-23 MONTHS BASED ON RECALL AND RECORD)'), (9, 'Unnamed: 9'), (10, 'Unnamed: 10'), (11, 'DIARRHOEA LAST 30 DAYS(UNDER 5 YEARS)'), (12, 'Unnamed: 12'), (13, 'Unnamed: 13')]

In [ ]:
# @title
# Full Imunization % - Function embedded in single function below also
# --- KPI DEFINITION: National Full Immunization ---
def calculate_national_full_immunization(df_health, selected_years_tuple):
    """
    Calculates the Average National Full Immunization Rate for the selected years.
    Logic: Average of 'FULL IMMUNISATION - Total' where Region is 'OVERALL'.
    """

    # 1. Create a working copy
    df = df_health.copy()

    # 2. Rename the specific column we identified
    # 'Unnamed: 10' is the Total (T) column for Full Immunization
    df.rename(columns={'Unnamed: 10': 'Full_Imm_Total'}, inplace=True)

    # 3. Filter for National Level data (Region = "OVERALL")
    df_national = df[df['Region'].astype(str).str.strip() == 'OVERALL'].copy()

    # 4. Clean the Data: Convert column to numeric
    # This removes any headers or text values that might cause errors
    df_national['Full_Imm_Total'] = pd.to_numeric(df_national['Full_Imm_Total'], errors='coerce')

    # 5. Apply the Dynamic Year Filter
    # Uses the master slicer variable to filter rows
    df_filtered = filter_by_selected_years(df_national, selected_years_tuple, year_col_name='Year')

    # 6. Calculate the KPI
    # Corresponds to: AVERAGE(Health[FULL IMMUNISATION - T])
    kpi_value = df_filtered['Full_Imm_Total'].mean()

    # 7. Display the Result
    if pd.isna(kpi_value):
        print(f"National Full Immunization: No Data for {selected_years_tuple}")
    else:
        print(f"National Full Immunization: {kpi_value:.2f}%")

    return kpi_value

# --- LINKING TO DASHBOARD ---
def update_dashboard(selected_years):
    print(f"--- DASHBOARD UPDATE (Selected Range: {selected_years}) ---")

    # 1. Calculate Literacy KPI (from previous step)
    if 'Education' in dataframes:
        calculate_national_adult_literacy(dataframes['Education'], selected_years)

    # 2. Calculate Immunization KPI (New)
    if 'Health' in dataframes:
        calculate_national_full_immunization(dataframes['Health'], selected_years)
    else:
        print("Error: 'Health.xlsx' not loaded.")

# Re-display the master interactive block
output_display = widgets.interactive_output(update_dashboard, {'selected_years': year_slicer_widget})
display(output_display)

Output()

In [ ]:
# @title
# Inspection code - non functional
# 1. Select the Household dataframe
df_household = dataframes['Household']

# 2. Inspect the Housing Tenure Section (Columns 12 to 19)
# We need to see the sub-headers to identify "Owned", "Rented", etc.
print("--- Housing Tenure Data (Cols 12-18) ---")
print(df_household.iloc[0:5, 12:19])

# 3. Check the unique regions in this specific section
# (Column index 13 is 'Region')
print("\n--- Unique Regions in Tenure Section ---")
print(df_household.iloc[:, 13].dropna().unique())

--- Housing Tenure Data (Cols 12-18) ---
      Year.2   Region  DISTRIBUTIONS OF HOUSEHOLDS BY HOUSING TENURE  \
0        NaN      NaN                                            OWN
1  2004-2005  OVERALL                                          86.57
2  2004-2005   Punjab                                          87.32
3  2004-2005    Sindh                                          87.33
4  2004-2005     NWFP                                          83.69

  Unnamed: 15 Unnamed: 16      Unnamed: 17 Unnamed: 18
0        RENT        FREE  SUBSIDISED RENT       TOTAL
1           7        5.32              1.1         100
2        6.57        5.15             0.95         100
3        6.94        4.79             0.93         100
4        8.22        6.66             1.43         100

--- Unique Regions in Tenure Section ---
['OVERALL' 'Punjab' 'Sindh' 'NWFP' 'Balochistan' 'KPK']

In [ ]:
# @title
# Adult literacy, immunization and home owners function - embedded below also
# --- KPI DEFINITION: % Home Owners ---
def calculate_home_ownership(df_household, selected_years_tuple):
    """
    Calculates the Average % Home Ownership for the selected years.
    Logic: Average of 'OWN' column in the Tenure section where Region is 'OVERALL'.
    """

    # 1. Extract only the relevant columns for Housing Tenure (Indices 12, 13, 14)
    # Index 12 = Year.2
    # Index 13 = Region
    # Index 14 = DISTRIBUTIONS... (which contains 'OWN' data)
    df_tenure = df_household.iloc[:, [12, 13, 14]].copy()

    # 2. Rename columns for clarity
    df_tenure.columns = ['Year', 'Region', 'Own_Percentage']

    # 3. Drop the first row (Row 0) which contains the sub-header "OWN"
    df_tenure = df_tenure.iloc[1:].copy()

    # 4. Filter for National Level data (Region = "OVERALL")
    df_national = df_tenure[df_tenure['Region'].astype(str).str.strip() == 'OVERALL'].copy()

    # 5. Clean the Data: Convert percentage column to numeric
    df_national['Own_Percentage'] = pd.to_numeric(df_national['Own_Percentage'], errors='coerce')

    # 6. Apply the Dynamic Year Filter
    # Note: We use the 'Year' column we renamed in step 2
    df_filtered = filter_by_selected_years(df_national, selected_years_tuple, year_col_name='Year')

    # 7. Calculate the KPI
    # Corresponds to: AVERAGE(Household_Ownership[Percentage]) where Type="OWN"
    kpi_value = df_filtered['Own_Percentage'].mean()

    # 8. Display the Result
    if pd.isna(kpi_value):
        print(f"Home Owners: No Data for {selected_years_tuple}")
    else:
        print(f"Home Owners: {kpi_value:.2f}%")

    return kpi_value

# --- LINKING TO DASHBOARD ---
def update_dashboard(selected_years):
    print(f"--- DASHBOARD UPDATE (Selected Range: {selected_years}) ---")

    # 1. Literacy KPI
    if 'Education' in dataframes:
        calculate_national_adult_literacy(dataframes['Education'], selected_years)

    # 2. Immunization KPI
    if 'Health' in dataframes:
        calculate_national_full_immunization(dataframes['Health'], selected_years)

    # 3. Home Ownership KPI (New)
    if 'Household' in dataframes:
        calculate_home_ownership(dataframes['Household'], selected_years)
    else:
        print("Error: 'Household.xlsx' not loaded.")

# Re-display the master interactive block
output_display = widgets.interactive_output(update_dashboard, {'selected_years': year_slicer_widget})
display(output_display)

Output()

In [ ]:
# @title
# Inspection code - non functional
# 1. Load Economy Data
df_economy = dataframes['Economy']

# 2. Inspect the first few rows to see the headers and data
print("--- First 5 Rows of Economy Data ---")
print(df_economy.head())

# 3. Check for unique values in the 'Region' column
# This tells us if we should filter for "Total", "Pakistan", or "OVERALL"
print("\n--- Unique Regions ---")
print(df_economy['Region'].dropna().unique())

# 4. Print column names to get the exact spelling for Income
print("\n--- Column List ---")
print(df_economy.columns.tolist())

--- First 5 Rows of Economy Data ---
        Year    Region  Avg Income per HouseHold  \
0  2001-2002     Urban                      9904
1  2001-2002     Rural                      6031
2  2001-2002  Pakistan                      7167
3  2004-2005     Urban                     13371
4  2004-2005     Rural                      7929

   Avg Consumpiton per HouseHold  Total Saving Per Households(Avg)
0                           8997                               907
1                           5766                               265
2                           6714                               453
3                          12079                              1292
4                           7712                               217

--- Unique Regions ---
['Urban' 'Rural' 'Pakistan']

--- Column List ---
['Year', 'Region', 'Avg Income per HouseHold', 'Avg Consumpiton per HouseHold', 'Total Saving Per Households(Avg)']

In [ ]:
# # Adult literacy, immunization home owners and avg national income function

# --- KPI DEFINITION: Average National Income ---
def calculate_avg_national_income(df_economy, selected_years_tuple):
    """
    Calculates the Average National Income for the selected years.
    Logic: Average of 'Avg Income per HouseHold' where Region is 'Pakistan'.
    """

    # 1. Create a working copy
    df = df_economy.copy()

    # 2. Filter for National Level data (Region = "Pakistan")
    # We strip whitespace to be safe ('Pakistan ' -> 'Pakistan')
    df_national = df[df['Region'].astype(str).str.strip() == 'Pakistan'].copy()

    # 3. Clean the Data: Convert Income column to numeric
    # The column name is exactly 'Avg Income per HouseHold' as per your inspection
    col_name = 'Avg Income per HouseHold'
    df_national[col_name] = pd.to_numeric(df_national[col_name], errors='coerce')

    # 4. Apply the Dynamic Year Filter
    df_filtered = filter_by_selected_years(df_national, selected_years_tuple, year_col_name='Year')

    # 5. Calculate the KPI
    # Corresponds to: AVERAGE(Economy[Avg Income per HouseHold])
    kpi_value = df_filtered[col_name].mean()

    # 6. Display the Result
    if pd.isna(kpi_value):
        print(f"Avg National Income: No Data for {selected_years_tuple}")
    else:
        # We format with commas for currency (e.g., 7,167.00)
        print(f"Avg National Income: {kpi_value:,.2f}")

    return kpi_value

# --- LINKING TO DASHBOARD ---
def update_dashboard(selected_years):
    print(f"--- DASHBOARD UPDATE (Selected Range: {selected_years}) ---")

    # 1. Literacy KPI
    if 'Education' in dataframes:
        calculate_national_adult_literacy(dataframes['Education'], selected_years)

    # 2. Immunization KPI
    if 'Health' in dataframes:
        calculate_national_full_immunization(dataframes['Health'], selected_years)

    # 3. Home Ownership KPI
    if 'Household' in dataframes:
        calculate_home_ownership(dataframes['Household'], selected_years)

    # 4. Avg National Income KPI (New)
    if 'Economy' in dataframes:
        calculate_avg_national_income(dataframes['Economy'], selected_years)
    else:
        print("Error: 'Economy.xlsx' not loaded.")

# Re-display the master interactive block
output_display = widgets.interactive_output(update_dashboard, {'selected_years': year_slicer_widget})
display(output_display)

Output()

In [ ]:
# Avg savings trend graph
import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION DIRECTLY ---
# We grab the values directly from the slider you created earlier
current_selection = year_slicer_widget.value

# Fallback: If nothing is selected, force select everything so we see something
if not current_selection:
    print("⚠️ No years selected in the slider. Selecting ALL years by default.")
    # Get all unique years from Economy file
    df_temp = dataframes['Economy']
    current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating chart for: {current_selection}")

# --- 2. PREPARE DATA ---
df = dataframes['Economy'].copy()

# Filter for National Level ('Pakistan')
df_national = df[df['Region'].astype(str).str.strip() == 'Pakistan'].copy()

# Clean Numeric Columns
col_income = 'Avg Income per HouseHold'
col_saving = 'Total Saving Per Households(Avg)'
for col in [col_income, col_saving]:
    df_national[col] = pd.to_numeric(df_national[col], errors='coerce')

# Filter by the years we grabbed
df_filtered = df_national[df_national['Year'].isin(current_selection)].copy()

# --- 3. CALCULATE & PLOT ---
if not df_filtered.empty:
    # Calculation
    df_filtered['Savings Rate'] = df_filtered[col_saving] / df_filtered[col_income]

    # Sorting
    df_filtered['Sort Year'] = df_filtered['Year'].astype(str).str[:4].astype(int)
    df_plot = df_filtered.sort_values(by='Sort Year')

    # Create Chart
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df_plot['Year'],
        y=df_plot['Savings Rate'],
        mode='lines+markers',
        name='Savings Rate',
        line=dict(color='darkgreen', width=3),
        marker=dict(size=8, color='darkgreen'),
        hovertemplate='<b>Year</b>: %{x}<br><b>Rate</b>: %{y:.2f}<extra></extra>'
    ))

    fig.update_layout(
        title='<b>AVG NATIONAL SAVINGS RATE TREND</b>',
        xaxis_title='Year',
        yaxis_title='Savings Rate',
        yaxis=dict(tickformat='.2f', range=[0, 0.16]),
        plot_bgcolor='white',
        hovermode="x unified",
        height=500
    )

    # FORCE DISPLAY
    fig.show()

    # Verify Data
    print("\nData used for this chart:")
    print(df_plot[['Year', 'Savings Rate']])

else:
    print("❌ No matching data found for these years in the Economy file.")

Generating chart for: ('2023', '2024')
❌ No matching data found for these years in the Economy file.

In [ ]:
# National Adult literacy trend graph
import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION DIRECTLY ---
current_selection = year_slicer_widget.value

# Fallback if empty
if not current_selection:
    df_temp = dataframes['Education']
    current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating Literacy Chart for: {current_selection}")

# --- 2. PREPARE DATA ---
df = dataframes['Education'].copy()

# Filter for National Level ('OVERALL')
# We strip whitespace just in case (' OVERALL ' -> 'OVERALL')
df_national = df[df['Region'].astype(str).str.strip() == 'OVERALL'].copy()

# Target Column: 'Unnamed: 13' is the Total Adult Literacy Rate
col_literacy = 'Unnamed: 13'

# Clean Numeric Columns
df_national[col_literacy] = pd.to_numeric(df_national[col_literacy], errors='coerce')

# Filter by the years we grabbed
df_filtered = df_national[df_national['Year'].isin(current_selection)].copy()

# --- 3. PLOT ---
if not df_filtered.empty:
    # Create Integer Year for the Axis
    df_filtered['Sort Year'] = df_filtered['Year'].astype(str).str[:4].astype(int)

    # Sort by this integer
    df_plot = df_filtered.sort_values(by='Sort Year')

    # Create Chart
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df_plot['Sort Year'],
        y=df_plot[col_literacy],
        mode='lines+markers',
        name='Literacy Rate',
        line=dict(color='#ED7D31', width=3), # Orange color matching screenshot
        marker=dict(size=8, color='#ED7D31'),
        hovertemplate='<b>Year</b>: %{x}<br><b>Rate</b>: %{y:.1f}%<extra></extra>'
    ))

    fig.update_layout(
        title=dict(text='<b>National Adult Literacy Rate Trend</b>', font=dict(size=18, color='black')),
        xaxis_title='Year',
        yaxis_title='Literacy Rate',

        # X-Axis Formatting
        xaxis=dict(
            tickmode='auto',
            nticks=10,
            tickformat="d" # Shows 2005, 2010 (no commas)
        ),

        yaxis=dict(
            range=[48, 60], # Adjusted to match your screenshot's Y-axis scale
            gridcolor='lightgrey'
        ),
        plot_bgcolor='#EDF5E6', # Light greenish background to match screenshot style (optional)
        paper_bgcolor='white',
        hovermode="x unified",
        height=500
    )

    # FORCE DISPLAY
    fig.show()

else:
    print("❌ No matching data found for Literacy Rate.")

Generating Literacy Chart for: ('2023', '2024')
❌ No matching data found for Literacy Rate.

In [ ]:
# @title
# Inspection code - non functional
# 1. Load Household Data
df_household = dataframes['Household']

# 2. Inspect the Toilet Section (Columns 8 to 11 likely)
# Based on previous turns, 'TYPE OF TOILET (% HOUSEHOLDS)' was around column 8
print("--- Toilet Data Section ---")
print(df_household.iloc[0:5, 8:12])

# 3. Check unique values in the 'Source' column for Toilet
# We need to find the exact string matching "NO-TOILET"
# Column 8 is likely the header, column 9 might be the source/category?
# Let's verify column 7 (Source.1) just in case
print("\n--- Unique Toilet Types (Column 7) ---")
print(df_household.iloc[:, 7].dropna().unique())

--- Toilet Data Section ---
  TYPE OF TOILET (% HOUSEHOLDS) Unnamed: 9 Unnamed: 10  Unnamed: 11
0                             U          R           T          NaN
1                            88         22          41          NaN
2                             6         15          12          NaN
3                             6         63          46          NaN
4                           100        100         100          NaN

--- Unique Toilet Types (Column 7) ---
['FLUSH' 'NON-FLUSH' 'NO-TOILET' 'TOTAL']

In [ ]:
# @title
# No toilet access guage - improved in below function
import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION DIRECTLY ---
current_selection = year_slicer_widget.value

# Fallback if empty
if not current_selection:
    df_temp = dataframes['Household']
    current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating Gauge for: {current_selection}")

# --- 2. PREPARE DATA ---
df = dataframes['Household'].copy()

# We need specific columns for the Toilet Section
# Col 6 = Year.1
# Col 7 = Source.1 (contains "NO-TOILET")
# Col 10 = Unnamed: 10 (contains the Total % value)
df_toilet = df.iloc[:, [6, 7, 10]].copy()
df_toilet.columns = ['Year', 'Toilet_Source', 'Percentage']

# Filter 1: Keep only "NO-TOILET" rows
# We strip whitespace to be safe
df_toilet = df_toilet[df_toilet['Toilet_Source'].astype(str).str.strip() == 'NO-TOILET']

# Clean Numeric Column
df_toilet['Percentage'] = pd.to_numeric(df_toilet['Percentage'], errors='coerce')

# Filter 2: Apply the Year Selection
# Note: This section uses 'Year.1' from the original file, which we renamed to 'Year'
df_filtered = df_toilet[df_toilet['Year'].isin(current_selection)].copy()

# --- 3. CALCULATE KPI ---
if not df_filtered.empty:
    # Calculate Average % over the selected years
    kpi_value = df_filtered['Percentage'].mean()

    # --- 4. PLOT GAUGE ---
    fig = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = kpi_value,
        domain = {'x': [0, 1], 'y': [0, 1]},
        title = {'text': "<b>No Toilet Access %</b>", 'font': {'size': 20}},
        gauge = {
            'axis': {'range': [0, 100], 'tickwidth': 1, 'tickcolor': "darkblue"},
            'bar': {'color': "darkgreen"}, # Matching the green in your screenshot
            'bgcolor': "white",
            'borderwidth': 2,
            'bordercolor': "gray",
            'steps': [
                {'range': [0, 100], 'color': "#f4f4f4"} # Light gray background arc
            ],
        }
    ))

    fig.update_layout(
        height=400,
        margin=dict(l=20, r=20, t=50, b=20),
        paper_bgcolor='white',
        font={'color': "black", 'family': "Arial"}
    )

    fig.show()

    print(f"Calculated Value: {kpi_value:.2f}%")

else:
    print("❌ No 'NO-TOILET' data found for the selected years.")

Generating Gauge for: ('2023', '2024')
❌ No 'NO-TOILET' data found for the selected years.

In [ ]:
# No toilet access % guage
import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    df_temp = dataframes['Household']
    current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating Gauge for: {current_selection}")

# --- 2. PREPARE DATA ---
df = dataframes['Household'].copy()

# Select relevant columns based on inspection
# Col 6 = Year (Year.1)
# Col 7 = Source (Source.1)
# Col 10 = The Weighted Total % (Unnamed: 10) -> THIS IS THE "REALITY" VALUE
df_toilet = df.iloc[:, [6, 7, 10]].copy()
df_toilet.columns = ['Year', 'Toilet_Source', 'Total_Percentage']

# Fill Down Year (Crucial for data alignment)
df_toilet['Year'] = df_toilet['Year'].ffill()

# Filter 1: Keep only "NO-TOILET" rows
df_toilet = df_toilet[df_toilet['Toilet_Source'].astype(str).str.strip() == 'NO-TOILET'].copy()

# Filter 2: Apply Year Selection
df_filtered = df_toilet[df_toilet['Year'].isin(current_selection)].copy()

# --- 3. CALCULATE KPI (WEIGHTED REALITY) ---
if not df_filtered.empty:
    # Convert to numeric
    df_filtered['Total_Percentage'] = pd.to_numeric(df_filtered['Total_Percentage'], errors='coerce')

    # Calculate the mean of the "Total" column
    # This preserves the population weighting inherent in the source data
    kpi_value = df_filtered['Total_Percentage'].mean()

    # --- 4. PLOT GAUGE ---
    fig = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = kpi_value,
        domain = {'x': [0, 1], 'y': [0, 1]},
        title = {'text': "<b>No Toilet Access %</b>", 'font': {'size': 18}},
        gauge = {
            'axis': {'range': [0, 100], 'tickwidth': 1, 'tickcolor': "darkblue"},
            'bar': {'color': "darkgreen"},
            'bgcolor': "white",
            'borderwidth': 2,
            'bordercolor': "gray",
            'steps': [
                {'range': [0, 100], 'color': "#f4f4f4"}
            ],
        }
    ))

    fig.update_layout(
        height=400,
        margin=dict(l=20, r=20, t=50, b=20),
        paper_bgcolor='white',
        font={'color': "black", 'family': "Arial"}
    )

    fig.show()
    print(f"Calculated Value: {kpi_value:.2f}")

else:
    print("❌ No 'NO-TOILET' data found.")

Generating Gauge for: ('2023', '2024')
❌ No 'NO-TOILET' data found.

In [ ]:
# @title
#inspection code - non functional

import pandas as pd

# 1. Load Household Data
df = dataframes['Household']

print("--- 1. WATER SECTION (Columns 0-5) ---")
# Usually Year, Source, Urban, Rural, Total
print(df.iloc[0:5, 0:6])

print("\n--- 2. TOILET SECTION (Columns 6-12) ---")
# Usually Year, Source, Urban, Rural, Total
print(df.iloc[0:5, 6:12])

print("\n--- 3. ELECTRICITY SECTION (Columns 20-25) ---")
# This section often has a different layout (Region column vs. U/R columns)
print(df.iloc[0:5, 20:25])

--- 1. WATER SECTION (Columns 0-5) ---
        Year       Source MAIN SOURCE OF DRINKING WATER Unnamed: 3 Unnamed: 4  \
0        NaN          NaN                             U          R          T
1  1998-1999  PIPED WATER                            55         12         26
2  1998-1999    HAND PUMP                            18         53         43
3  1998-1999   MOTOR PUMP                            20         12         14
4  1998-1999     DUG WELL                             2         11          8

   Unnamed: 5
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

--- 2. TOILET SECTION (Columns 6-12) ---
      Year.1   Source.1 TYPE OF TOILET (% HOUSEHOLDS) Unnamed: 9 Unnamed: 10  \
0        NaN        NaN                             U          R           T
1  1998-1999      FLUSH                            88         22          41
2  1998-1999  NON-FLUSH                             6         15          12
3  1998-1999  NO-TOILET                             6         63          46
4  1998-1999      TOTAL                           100        100         100

   Unnamed: 11
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

--- 3. ELECTRICITY SECTION (Columns 20-25) ---
      Year.3 Region.1 Feul used Lighting Unnamed: 23 Unnamed: 24
0        NaN      NaN       Electricity      Gas/Oil      Candle
1  2004-2005   Urban                96.4        3.41        0.08
2  2004-2005    Rural              74.27       24.76        0.23
3  2004-2005    Total              83.85       15.52        0.16
4  2006-2007   Urban               97.58        2.14         0.1

In [ ]:
#urban vs rural basic access disparity check

import plotly.graph_objects as go
import pandas as pd
import numpy as np

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    # Default to all years if nothing selected
    df_temp = dataframes['Household']
    current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating Disparity Chart for: {current_selection}")

# --- 2. SETUP ---
df = dataframes['Household'].copy()
categories = ['Electricity', 'Flush Toilet', 'Tap Water']
urban_vals = []
rural_vals = []

# --- 3. DATA EXTRACTION ---

# [A] ELECTRICITY (Cols 20-22)
# Structure: Year(20) | Region(21) | Value(22)
df_elec = df.iloc[:, [20, 21, 22]].copy()
df_elec.columns = ['Year', 'Region', 'Percentage']
df_elec.loc[:, 'Year'] = df_elec['Year'].ffill() # Fix Warning

# Filter
subset_elec = df_elec[df_elec['Year'].isin(current_selection)].copy()
subset_elec.loc[:, 'Percentage'] = pd.to_numeric(subset_elec['Percentage'], errors='coerce')

# Extract Values (Use MAX to be safe)
u_elec = subset_elec[subset_elec['Region'].astype(str).str.strip().str.lower() == 'urban']['Percentage'].max()
r_elec = subset_elec[subset_elec['Region'].astype(str).str.strip().str.lower() == 'rural']['Percentage'].max()

urban_vals.append(u_elec)
rural_vals.append(r_elec)


# [B] FLUSH TOILET (Cols 6-9)
# Structure: Year(6) | Source(7) | Urban(8) | Rural(9)
# REMOVED: The check for 'MainRegion' (Col 1) as it was incorrect.
df_toilet = df.iloc[:, [6, 7, 8, 9]].copy()
df_toilet.columns = ['Year', 'Source', 'Urban', 'Rural']
df_toilet.loc[:, 'Year'] = df_toilet['Year'].ffill()

# Filter: Year + Source="FLUSH"
subset_toilet = df_toilet[
    (df_toilet['Year'].isin(current_selection)) &
    (df_toilet['Source'].astype(str).str.strip() == 'FLUSH')
].copy()

subset_toilet.loc[:, 'Urban'] = pd.to_numeric(subset_toilet['Urban'], errors='coerce')
subset_toilet.loc[:, 'Rural'] = pd.to_numeric(subset_toilet['Rural'], errors='coerce')

urban_vals.append(subset_toilet['Urban'].max())
rural_vals.append(subset_toilet['Rural'].max())


# [C] TAP WATER (Cols 0-3)
# Structure: Year(0) | Source(1) | Urban(2) | Rural(3)
df_water = df.iloc[:, [0, 1, 2, 3]].copy()
df_water.columns = ['Year', 'Source', 'Urban', 'Rural']
df_water.loc[:, 'Year'] = df_water['Year'].ffill()

# Filter: Year + Source="PIPED WATER"
subset_water = df_water[
    (df_water['Year'].isin(current_selection)) &
    (df_water['Source'].astype(str).str.contains('PIPED', case=False, na=False))
].copy()

subset_water.loc[:, 'Urban'] = pd.to_numeric(subset_water['Urban'], errors='coerce')
subset_water.loc[:, 'Rural'] = pd.to_numeric(subset_water['Rural'], errors='coerce')

urban_vals.append(subset_water['Urban'].max())
rural_vals.append(subset_water['Rural'].max())

# --- 4. CLEANUP & FEEDBACK ---
urban_vals = [0 if pd.isna(x) else x for x in urban_vals]
rural_vals = [0 if pd.isna(x) else x for x in rural_vals]

print("\n--- Final Data Check ---")
print(f"Electricity: Urban={urban_vals[0]:.1f}%, Rural={rural_vals[0]:.1f}%")
print(f"Flush Toilet: Urban={urban_vals[1]:.1f}%, Rural={rural_vals[1]:.1f}%")
print(f"Tap Water:   Urban={urban_vals[2]:.1f}%, Rural={rural_vals[2]:.1f}%")

# --- 5. PLOT CHART ---
fig = go.Figure()

fig.add_trace(go.Bar(
    x=categories,
    y=urban_vals,
    name='Urban',
    marker_color='#114f1e',
    text=[f'{x:.0f}%' if x > 0 else '' for x in urban_vals],
    textposition='auto'
))

fig.add_trace(go.Bar(
    x=categories,
    y=rural_vals,
    name='Rural',
    marker_color='#8bc34a',
    text=[f'{x:.0f}%' if x > 0 else '' for x in rural_vals],
    textposition='auto'
))

fig.update_layout(
    title='<b>Urban vs. Rural Basic Access Disparity</b>',
    xaxis_title='',
    yaxis_title='Percentage (%)',
    barmode='group',
    plot_bgcolor='white',
    legend=dict(orientation="h", y=1.02, x=1),
    height=500,
    yaxis=dict(range=[0, 105])
)

fig.show()

Generating Disparity Chart for: ('2023', '2024')

--- Final Data Check ---
Electricity: Urban=0.0%, Rural=0.0%
Flush Toilet: Urban=0.0%, Rural=0.0%
Tap Water:   Urban=0.0%, Rural=0.0%

In [ ]:
# @title
#inspection code - non functional
import pandas as pd

# 1. Load Employment Data (or check keys if already loaded)
# Assuming the file is named 'Employment.xlsx' or similar
try:
    if 'Employment' in dataframes:
        df = dataframes['Employment']
    else:
        df = pd.read_excel('Employment.xlsx')

    print("--- RAW DATA INSPECTION: EMPLOYMENT ---")
    print(df.head(10))

    # Check for "Agriculture" in the data to pinpoint the column
    print("\n--- Searching for 'Agriculture' ---")
    # Search all text columns for the word "Agriculture"
    for col in df.select_dtypes(include=['object']):
        if df[col].astype(str).str.contains('Agriculture', case=False).any():
            print(f"Found 'Agriculture' in Column: {col}")
            print(df[col].unique())

except Exception as e:
    print(f"Error checking Employment data: {e}")

--- RAW DATA INSPECTION: EMPLOYMENT ---
        Year      Area Employement Unnamed: 3   Unnamed: 4       Unnamed: 5  \
0        NaN       NaN       Total   Employer  Agriculture  Non-Agriculture
1  2001-2002     Urban         100       1.71         2.01            19.44
2  2001-2002     Rural         100       0.76         19.4            10.37
3  2001-2002  Pakistan         100       1.02        14.74             12.8
4  2004-2005     Urban         100       0.63         2.52            29.57
5  2004-2005     Rural         100       0.19        23.28            14.15
6  2004-2005  Pakistan         100       0.32        17.16             18.7
7  2005-2006     Urban         100       1.85         2.51            20.24
8  2005-2006     Rural         100       0.74        20.42             10.2
9  2005-2006  Pakistan         100       1.09        14.78            13.36

  Unnamed: 6 Unnamed: 7
0     Unpaid   Employee
1      11.96      64.88
2      35.33      34.14
3      29.07      42.38
4      11.09      56.19
5      29.59      32.79
6      24.13      39.69
7      10.69      64.71
8      30.26      38.39
9      24.11      46.67

--- Searching for 'Agriculture' ---
Found 'Agriculture' in Column: Unnamed: 4
['Agriculture' 2.01 19.4 14.74 2.52 23.28 17.16 2.51 20.42 14.78 2.46
 19.15 13.92 1.8 18.66 13.22 18.6 13.35 2.18 21.96 15.41 1.92 18.57 2.56
 17.98 12.53]
Found 'Agriculture' in Column: Unnamed: 5
['Non-Agriculture' 19.44 10.37 12.8 29.57 14.15 18.7 20.24 10.2 13.36
 15.14 9.52 11.28 16.51 9.35 11.66 17.14 9.91 12.17 16.92 9.09 11.68 16.54
 8.68 18.49 9.59 12.74]

In [ ]:
# @title
#power bi measurements - not preferred use below one

import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Employment' in dataframes:
        df_temp = dataframes['Employment']
        current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating Structural Shift Chart for: {current_selection}")

# --- 2. PREPARE DATA ---
if 'Employment' in dataframes:
    df = dataframes['Employment'].copy()

    # Select Columns based on inspection
    # Year(0), Agriculture(4), Non-Agriculture(5)
    df_shift = df.iloc[:, [0, 4, 5]].copy()
    df_shift.columns = ['Year', 'Agriculture', 'Non_Agriculture']

    # Fill down Year (Crucial for Power BI logic)
    df_shift['Year'] = df_shift['Year'].ffill()

    # Clean Numeric Columns
    for col in ['Agriculture', 'Non_Agriculture']:
        df_shift[col] = pd.to_numeric(df_shift[col], errors='coerce')

    # Filter by Year Selection
    df_filtered = df_shift[df_shift['Year'].isin(current_selection)].copy()

    # --- 3. CALCULATE AVERAGES (POWER BI STYLE) ---
    # Instead of filtering for "Pakistan", we group by Year and take the mean of ALL rows (Urban, Rural, Pakistan)
    # This replicates the behavior of CALCULATE(AVERAGE(Employment[Percentage])) without region filters.
    df_grouped = df_filtered.groupby('Year')[['Agriculture', 'Non_Agriculture']].mean().reset_index()

    # Create Sort Year (Integer) for Axis
    df_grouped['SortYear'] = df_grouped['Year'].astype(str).str[:4].astype(int)
    df_plot = df_grouped.sort_values(by='SortYear')

    # --- 4. PLOT CHART ---
    fig = go.Figure()

    # Agriculture Line (Green)
    fig.add_trace(go.Scatter(
        x=df_plot['SortYear'],
        y=df_plot['Agriculture'],
        mode='lines+markers',
        name='% in Agriculture',
        line=dict(color='#2ca02c', width=3),
        marker=dict(size=8),
        hovertemplate='<b>Year</b>: %{x}<br><b>Ag</b>: %{y:.2f}%<extra></extra>'
    ))

    # Non-Agriculture Line (Blue)
    fig.add_trace(go.Scatter(
        x=df_plot['SortYear'],
        y=df_plot['Non_Agriculture'],
        mode='lines+markers',
        name='% in Non-Agriculture',
        line=dict(color='#1f77b4', width=3),
        marker=dict(size=8),
        hovertemplate='<b>Year</b>: %{x}<br><b>Non-Ag</b>: %{y:.2f}%<extra></extra>'
    ))

    fig.update_layout(
        title='<b>Workforce Structural Shift</b>',
        xaxis_title='Year',
        yaxis_title='Percentage (%)',
        xaxis=dict(
            tickmode='auto',
            nticks=10,
            tickformat="d" # Integer years (2004, 2005...)
        ),
        yaxis=dict(gridcolor='lightgrey'),
        plot_bgcolor='white',
        hovermode="x unified",
        legend=dict(orientation="h", y=1.02, x=0.5, xanchor="center"),
        height=500
    )

    fig.show()

    # Validation Print
    print("\n--- Sample Values (Power BI Logic) ---")
    print(df_plot[['Year', 'Agriculture', 'Non_Agriculture']].head())

else:
    print("Error: Employment.xlsx not loaded.")

Generating Structural Shift Chart for: ('2001-2002', '2004-2005', '2005-2006', '2006-2007', '2007-2008', '2008-2009')

--- Sample Values (Power BI Logic) ---
        Year  Agriculture  Non_Agriculture
0  2001-2002    12.050000        14.203333
1  2004-2005    14.320000        20.806667
2  2005-2006    12.570000        14.600000
3  2007-2008    11.843333        11.980000

In [ ]:
#Workforce Structural shift actual measurements - preferred

import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Employment' in dataframes:
        df_temp = dataframes['Employment']
        current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating ACCURATE Structural Shift Chart for: {current_selection}")

# --- 2. PREPARE DATA (ACCURATE METHOD) ---
if 'Employment' in dataframes:
    df = dataframes['Employment'].copy()

    # Select Columns: Year(0), Area(1), Agriculture(4), Non-Agriculture(5)
    df_shift = df.iloc[:, [0, 1, 4, 5]].copy()
    df_shift.columns = ['Year', 'Area', 'Agriculture', 'Non_Agriculture']

    # Filter 1: STRICTLY National Level ('Pakistan')
    # This avoids the "Double Counting" error and uses the correct population weights
    df_shift = df_shift[df_shift['Area'].astype(str).str.strip() == 'Pakistan'].copy()

    # Clean Numeric Columns
    for col in ['Agriculture', 'Non_Agriculture']:
        df_shift[col] = pd.to_numeric(df_shift[col], errors='coerce')

    # Filter 2: Year Selection
    df_filtered = df_shift[df_shift['Year'].isin(current_selection)].copy()

    # Create Sort Year (Integer) for Axis
    df_filtered['SortYear'] = df_filtered['Year'].astype(str).str[:4].astype(int)
    df_plot = df_filtered.sort_values(by='SortYear')

    # --- 3. PLOT CHART ---
    fig = go.Figure()

    # Agriculture Line (Green)
    fig.add_trace(go.Scatter(
        x=df_plot['SortYear'],
        y=df_plot['Agriculture'],
        mode='lines+markers',
        name='Agriculture',
        line=dict(color='#2ca02c', width=3),
        marker=dict(size=8),
        hovertemplate='<b>Year</b>: %{x}<br><b>Ag</b>: %{y:.2f}%<extra></extra>'
    ))

    # Non-Agriculture Line (Blue)
    fig.add_trace(go.Scatter(
        x=df_plot['SortYear'],
        y=df_plot['Non_Agriculture'],
        mode='lines+markers',
        name='Non-Agriculture',
        line=dict(color='#1f77b4', width=3),
        marker=dict(size=8),
        hovertemplate='<b>Year</b>: %{x}<br><b>Non-Ag</b>: %{y:.2f}%<extra></extra>'
    ))

    fig.update_layout(
        title='<b>Workforce Structural Shift (Statistically Accurate)</b>',
        xaxis_title='Year',
        yaxis_title='Percentage (%)',
        xaxis=dict(
            tickmode='auto',
            nticks=10,
            tickformat="d" # Integer years (2004, 2005...)
        ),
        yaxis=dict(gridcolor='lightgrey'),
        plot_bgcolor='white',
        hovermode="x unified",
        legend=dict(orientation="h", y=1.02, x=0.5, xanchor="center"),
        height=500
    )

    fig.show()

    # Verification Print
    print("\n--- Accurate National Values (Pakistan Row) ---")
    print(df_plot[['Year', 'Agriculture', 'Non_Agriculture']].head())

else:
    print("Error: Employment.xlsx not loaded.")

Generating ACCURATE Structural Shift Chart for: ('2001-2002', '2004-2005', '2005-2006', '2006-2007', '2007-2008', '2008-2009')

--- Accurate National Values (Pakistan Row) ---
         Year  Agriculture  Non_Agriculture
3   2001-2002        14.74            12.80
6   2004-2005        17.16            18.70
9   2005-2006        14.78            13.36
12  2007-2008        13.92            11.28

In [ ]:
#Page 03
#Literacy Gender Gap
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Education' in dataframes:
        df_temp = dataframes['Education']
        current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Calculating Average Gap for: {current_selection}")

# --- 2. CALCULATE VALUE ---
if 'Education' in dataframes:
    df = dataframes['Education'].copy()

    # Columns: Year(0), Region(1), Male(11), Total(13)
    # We verify these indices based on standard file layout
    df_gap = df.iloc[:, [0, 1, 11, 13]].copy()
    df_gap.columns = ['Year', 'Region', 'Male', 'Total']

    # Filter 1: National Level ('OVERALL')
    df_gap = df_gap[df_gap['Region'].astype(str).str.strip().str.upper() == 'OVERALL'].copy()

    # Filter 2: Selected Years
    df_filtered = df_gap[df_gap['Year'].isin(current_selection)].copy()

    # Convert to numeric
    df_filtered['Male'] = pd.to_numeric(df_filtered['Male'], errors='coerce')
    df_filtered['Total'] = pd.to_numeric(df_filtered['Total'], errors='coerce')

    # --- 3. COMPUTE AVERAGE GAP ---
    # Formula: Average(Male) - Average(Total)
    avg_male = df_filtered['Male'].mean()
    avg_total = df_filtered['Total'].mean()
    avg_gap = avg_male - avg_total

    # --- 4. DISPLAY RESULT ---
    print("\n" + "="*40)
    print(f"  LITERACY GENDER GAP (Average)")
    print("="*40)
    print(f"  Avg Male Rate:   {avg_male:.2f}%")
    print(f"  Avg Total Rate:  {avg_total:.2f}%")
    print("-" * 25)
    print(f"  GAP VALUE:       {avg_gap:.2f}%")
    print("="*40)

else:
    print("Error: Education.xlsx not loaded.")

Calculating Average Gap for: ('2023', '2024')

========================================
  LITERACY GENDER GAP (Average)
========================================
  Avg Male Rate:   nan%
  Avg Total Rate:  nan%
-------------------------
  GAP VALUE:       nan%
========================================

In [ ]:
#Full immunization rate
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    # Check if 'Health' exists, otherwise fallback to Household or similar
    if 'Health' in dataframes:
        df_temp = dataframes['Health']
    elif 'Household' in dataframes: # Sometimes health data is in Household
        df_temp = dataframes['Household']

    if 'Year' in df_temp.columns:
        current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Calculating Full Immunization Rate for: {current_selection}")

# --- 2. PREPARE DATA ---
# We need to find the "Health" data.
# Strategy: Check 'Health' dataframe first, then 'Household' columns.
target_col = None
df_health = None

if 'Health' in dataframes:
    df_health = dataframes['Health'].copy()
    # Look for "FULL IMMUNISATION - T" or similar column
    for col in df_health.columns:
        if "FULL" in str(col).upper() and "IMMUNI" in str(col).upper() and ("T" in str(col).upper() or "TOTAL" in str(col).upper()):
            target_col = col
            break
elif 'Household' in dataframes:
    # Sometimes Health is a section in Household.xlsx
    df_health = dataframes['Household'].copy()
    # Search columns by name or index.
    # Based on standard layout, if it exists here, we need to find it.
    for col in df_health.columns:
         if "FULL" in str(col).upper() and "IMMUNI" in str(col).upper():
            target_col = col
            break

# --- 3. CALCULATE VALUE ---
if df_health is not None and target_col:
    # Filter by Year
    # Ensure Year column exists and is filled
    if 'Year' in df_health.columns:
         df_health['Year'] = df_health['Year'].ffill()
         df_filtered = df_health[df_health['Year'].isin(current_selection)].copy()
    else:
         # Fallback: Assume rows correspond to years if structure implies it,
         # but strict filtering requires a Year column.
         df_filtered = df_health.copy()

    # Convert to Numeric
    df_filtered[target_col] = pd.to_numeric(df_filtered[target_col], errors='coerce')

    # Calculate Average
    avg_immunization = df_filtered[target_col].mean()

    # --- 4. DISPLAY RESULT ---
    print("\n" + "="*40)
    print(f"  FULL IMMUNIZATION RATE (Average)")
    print("="*40)
    print(f"  Selected Years:  {len(df_filtered)} records")
    print("-" * 25)
    print(f"  AVERAGE VALUE:   {avg_immunization:.2f}%")
    print("="*40)

else:
    print("Error: Could not find 'Health' data or 'Full Immunization' column.")
    print("Available Dataframes:", dataframes.keys())

Calculating Full Immunization Rate for: ('2023', '2024')

========================================
  FULL IMMUNIZATION RATE (Average)
========================================
  Selected Years:  0 records
-------------------------
  AVERAGE VALUE:   nan%
========================================

In [ ]:
#Literacy Rate average

import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Education' in dataframes:
        df_temp = dataframes['Education']
        current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Calculating Total Literacy Rate for: {current_selection}")

# --- 2. PREPARE DATA ---
if 'Education' in dataframes:
    df = dataframes['Education'].copy()

    # Columns based on previous inspection:
    # Year(0), Region(1), Total Rate(13)
    df_lit = df.iloc[:, [0, 1, 13]].copy()
    df_lit.columns = ['Year', 'Region', 'Total_Rate']

    # Filter 1: National Level ('OVERALL')
    # This ensures we get the official national statistic
    df_lit = df_lit[df_lit['Region'].astype(str).str.strip().str.upper() == 'OVERALL'].copy()

    # Filter 2: Year Selection
    df_filtered = df_lit[df_lit['Year'].isin(current_selection)].copy()

    # Convert to numeric
    df_filtered['Total_Rate'] = pd.to_numeric(df_filtered['Total_Rate'], errors='coerce')

    # --- 3. CALCULATE AVERAGE ---
    avg_literacy = df_filtered['Total_Rate'].mean()

    # --- 4. DISPLAY RESULT ---
    print("\n" + "="*40)
    print(f"  TOTAL LITERACY RATE (National)")
    print("="*40)
    print(f"  Selected Years:  {len(df_filtered)}")
    print("-" * 25)
    print(f"  AVERAGE VALUE:   {avg_literacy:.2f}%")
    print("="*40)

else:
    print("Error: Education.xlsx not loaded.")

Calculating Total Literacy Rate for: ('2001-2002', '2004-2005', '2005-2006')

========================================
  TOTAL LITERACY RATE (National)
========================================
  Selected Years:  3
-------------------------
  AVERAGE VALUE:   48.00%
========================================

In [ ]:
# @title
#Inspection code - non functional
import pandas as pd

# --- 1. LOAD DATA ---
try:
    # Use existing dict or load file
    if 'Health' in dataframes:
        df = dataframes['Health'].copy()
    else:
        df = pd.read_excel('Health.xlsx')

    print("--- RAW DATA INSPECTION: DIARRHOEA ---")

    # --- 2. FIND COLUMN ---
    target_col = None
    for col in df.columns:
        if "DIARRHOEA" in str(col).upper() and "30 DAYS" in str(col).upper() and ("T" in str(col).upper() or "TOTAL" in str(col).upper()):
            target_col = col
            break

    # --- 3. ANALYZE VALUES ---
    if target_col:
        print(f"Found Column: {target_col}")

        # Force numeric
        vals = pd.to_numeric(df[target_col], errors='coerce').dropna()

        print("\n--- Sample Values (First 5) ---")
        print(vals.head(5).to_string(index=False))

        max_val = vals.max()
        min_val = vals.min()

        print(f"\n--- Statistics ---")
        print(f"Minimum Value: {min_val}")
        print(f"Maximum Value: {max_val}")

        print("\n--- VERDICT ---")
        if max_val > 100:
            print("✅ CONFIRMED: These are COUNTS (Total Incidents).")
        else:
            print("✅ CONFIRMED: These are PERCENTAGES (Incidence Rate).")

    else:
        print("❌ Could not find 'Diarrhoea' column.")

except Exception as e:
    print(f"Error: {e}")

--- RAW DATA INSPECTION: DIARRHOEA ---
Found Column: DIARRHOEA LAST 30 DAYS(UNDER 5 YEARS)

--- Sample Values (First 5) ---
14.0
14.0
11.0
18.0
13.0

--- Statistics ---
Minimum Value: 4.0
Maximum Value: 19.0

--- VERDICT ---
✅ CONFIRMED: These are PERCENTAGES (Incidence Rate).

In [ ]:
#Diarohea incidence trend graph
import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Health' in dataframes:
        df_temp = dataframes['Health']
        current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating Diarrhoea Incidence Trend for: {current_selection}")

# --- 2. PREPARE DATA ---
if 'Health' in dataframes:
    df = dataframes['Health'].copy()

    # Search for Column
    target_col = None
    for col in df.columns:
        if "DIARRHOEA" in str(col).upper() and "30 DAYS" in str(col).upper():
            target_col = col
            break

    if target_col:
        # Standardize
        df_health = df.iloc[:, [0, 1]].copy()
        df_health['Value'] = df[target_col]
        df_health.columns = ['Year', 'Region', 'Value']

        # Filter 1: National Level ('OVERALL')
        # This gives the accurate National Rate
        df_health = df_health[df_health['Region'].astype(str).str.strip().str.upper() == 'OVERALL'].copy()

        # Filter 2: Year Selection
        df_filtered = df_health[df_health['Year'].isin(current_selection)].copy()

        # Numeric Conversion
        df_filtered['Value'] = pd.to_numeric(df_filtered['Value'], errors='coerce')

        # Sort by Year for Line Chart
        df_filtered['SortYear'] = df_filtered['Year'].astype(str).str[:4].astype(int)
        df_plot = df_filtered.sort_values(by='SortYear')

        # --- 3. PLOT CHART ---
        fig = go.Figure()

        fig.add_trace(go.Scatter(
            x=df_plot['SortYear'],
            y=df_plot['Value'],
            mode='lines+markers',
            name='Incidence Rate',
            line=dict(color='#d62728', width=3), # Red for Health Alert
            marker=dict(size=8),
            hovertemplate='<b>Year</b>: %{x}<br><b>Rate</b>: %{y:.1f}%<extra></extra>'
        ))

        fig.update_layout(
            title='<b>Diarrhoea Incidence Trend (National)</b>',
            xaxis_title='Year',
            yaxis_title='Incidence Rate (%)',
            xaxis=dict(tickmode='auto', nticks=10, tickformat="d"),
            yaxis=dict(gridcolor='lightgrey', range=[0, 25]), # Scale 0-25% appropriate for values 4-19
            plot_bgcolor='white',
            hovermode="x unified",
            height=400
        )

        fig.show()

    else:
        print("Error: Diarrhoea column not found.")

else:
    print("Error: Health.xlsx not loaded.")

Generating Diarrhoea Incidence Trend for: ('2023', '2024')

In [ ]:
#Provincial immunization chart

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Health' in dataframes:
        df_temp = dataframes['Health']
        current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Generating Provincial Ranking (NWFP -> KPK) for: {current_selection}")

# --- 2. PREPARE DATA ---
if 'Health' in dataframes:
    # Work on a copy so we don't touch the original file
    df = dataframes['Health'].copy()

    # Identify Target Column
    target_col = None
    for col in df.columns:
        if "FULL" in str(col).upper() and "IMMUNI" in str(col).upper() and ("T" in str(col).upper() or "TOTAL" in str(col).upper()):
            target_col = col
            break

    if target_col:
        # Standardize Columns
        df_health = df.iloc[:, [0, 1]].copy()
        df_health['Value'] = df[target_col]
        df_health.columns = ['Year', 'Region', 'Value']

        # --- VISUALIZATION-SPECIFIC ADJUSTMENTS ---
        # 1. Remove rows strictly labeled 'KPK' (ignore them for this chart)
        df_health = df_health[df_health['Region'].astype(str).str.strip().str.upper() != 'KPK'].copy()

        # 2. Rename 'NWFP' to 'KPK'
        # This effectively merges the old name into the new label
        df_health['Region'] = df_health['Region'].replace({
            'NWFP': 'KPK',
            'N.W.F.P': 'KPK',
            'North West Frontier Province': 'KPK'
        })
        # ------------------------------------------

        # Filter 1: Exclude 'OVERALL' to rank only provinces
        df_prov = df_health[~df_health['Region'].astype(str).str.strip().str.upper().isin(['OVERALL', 'PAKISTAN'])].copy()

        # Filter 2: Year Selection
        df_filtered = df_prov[df_prov['Year'].isin(current_selection)].copy()

        # Convert to Numeric
        df_filtered['Value'] = pd.to_numeric(df_filtered['Value'], errors='coerce')

        # --- 3. CALCULATE RANKING ---
        # Group by the NEW Region names (where NWFP is now KPK)
        df_rank = df_filtered.groupby('Region')['Value'].mean().reset_index()

        # Sort Descending (Highest at top)
        df_rank = df_rank.sort_values(by='Value', ascending=True)

        # --- 4. PLOT CHART ---
        fig = go.Figure()

        fig.add_trace(go.Bar(
            y=df_rank['Region'],
            x=df_rank['Value'],
            orientation='h',
            marker=dict(color='orange'),
            text=[f'{x:.1f}%' for x in df_rank['Value']],
            textposition='auto'
        ))

        fig.update_layout(
            title='<b>Provincial Immunization Ranking</b>',
            xaxis_title='Immunization Rate (%)',
            yaxis_title='',
            xaxis=dict(range=[0, 100]),
            plot_bgcolor='white',
            height=400
        )

        fig.show()

    else:
        print("Error: 'Full Immunisation' column not found.")

else:
    print("Error: Health.xlsx not loaded.")

Generating Provincial Ranking (NWFP -> KPK) for: ('2023', '2024')

In [ ]:
#Literacy trends and Gender Parity Index GPI overtime

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import numpy as np

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Education' in dataframes:
        df_temp = dataframes['Education']
        current_selection = tuple(df_temp['Year'].dropna().unique())

# --- 2. PREPARE DATA ---
if 'Education' in dataframes:
    df = dataframes['Education'].copy()
    adult_col = next((col for col in df.columns if "ADULT" in str(col).upper() and "T" in str(col).upper()), None)

    cols_to_use = [0, 1, 11, 13]
    df_trends = df.iloc[:, cols_to_use].copy()
    df_trends.columns = ['Year', 'Region', 'Male_10', 'Total_10']

    if adult_col:
        df_trends['Adult_Total'] = df[adult_col]
    else:
        df_trends['Adult_Total'] = np.nan

    df_trends = df_trends[df_trends['Region'].astype(str).str.strip().str.upper() == 'OVERALL'].copy()
    df_filtered = df_trends[df_trends['Year'].isin(current_selection)].copy()

    for col in ['Male_10', 'Total_10', 'Adult_Total']:
        df_filtered[col] = pd.to_numeric(df_filtered[col], errors='coerce')

    # CALCULATE GAP (DAX: Male - Total)
    df_filtered['Gender_Gap'] = df_filtered['Male_10'] - df_filtered['Total_10']
    df_filtered['SortYear'] = df_filtered['Year'].astype(str).str[:4].astype(int)
    df_plot = df_filtered.sort_values(by='SortYear')

    # --- 3. PLOT DUAL-AXIS CHART ---
    fig = make_subplots(specs=[[{"secondary_y": True}]])

    # Trace 1: Literacy Rate 10+
    fig.add_trace(
        go.Scatter(x=df_plot['SortYear'], y=df_plot['Total_10'],
                   name="Literacy 10+ (Total)", line=dict(color="#1f77b4", width=3),
                   mode='lines+markers'),
        secondary_y=False,
    )

    # Trace 2: Adult Literacy Rate
    if not df_plot['Adult_Total'].isna().all():
        fig.add_trace(
            go.Scatter(x=df_plot['SortYear'], y=df_plot['Adult_Total'],
                       name="Adult Literacy (Total)", line=dict(color="#FF8C00", width=3),
                       mode='lines+markers'),
            secondary_y=False,
        )

    # Trace 3: Gender Gap (ENHANCED WITH DATA POINTS/LABELS)
    fig.add_trace(
        go.Scatter(x=df_plot['SortYear'],
                   y=df_plot['Gender_Gap'],
                   name="Gender Gap (M - T)",
                   line=dict(color="purple", width=2, dash='dot'),
                   mode='lines+markers+text', # Added 'text' to show points
                   text=[f'{v:.1f}' for v in df_plot['Gender_Gap']], # Format the labels
                   textposition="top center", # Position labels above the points
                   marker=dict(size=10, symbol='diamond')), # Larger diamond markers for visibility
        secondary_y=True,
    )

    # --- 4. STYLING ---
    fig.update_layout(
        title='<b>Literacy Trends & Gender Parity</b>',
        xaxis_title='Year',
        plot_bgcolor='white',
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=550,
        margin=dict(t=120)
    )

    # Primary Y-Axis (Literacy)
    fig.update_yaxes(title_text="<b>Literacy Rate (%)</b>", secondary_y=False, range=[0, 105], gridcolor='lightgrey')

    # Secondary Y-Axis (Gap) - Range tightened to 0-20 to "zoom in" on small gap values
    fig.update_yaxes(title_text="<b>Gender Gap (%)</b>", secondary_y=True, range=[0, 20], showgrid=False)

    fig.show()

else:
    print("Error: 'Education' sheet not found in dataframes.")

In [ ]:
#Literacy Rate composition by gender - Bar chart
import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Education' in dataframes:
        df_temp = dataframes['Education']
        current_selection = tuple(df_temp['Year'].dropna().unique())

# --- 2. PREPARE DATA (Power BI Simple Average Logic) ---
if 'Education' in dataframes:
    df = dataframes['Education'].copy()

    # Year(0), Male(11), Female(12)
    df_gender = df.iloc[:, [0, 11, 12]].copy()
    df_gender.columns = ['Year', 'Male', 'Female']

    # Filter by Year
    df_filtered = df_gender[df_gender['Year'].isin(current_selection)].copy()

    # Convert to Numeric
    df_filtered['Male'] = pd.to_numeric(df_filtered['Male'], errors='coerce')
    df_filtered['Female'] = pd.to_numeric(df_filtered['Female'], errors='coerce')

    # Calculate Average across all rows per year (Power BI DAX style)
    df_plot = df_filtered.groupby('Year').mean().reset_index()

    # Sort by Year
    df_plot['SortYear'] = df_plot['Year'].astype(str).str[:4].astype(int)
    df_plot = df_plot.sort_values(by='SortYear')

    # --- 3. PLOT CHART ---
    fig = go.Figure()

    # Male Bar
    fig.add_trace(go.Bar(
        x=df_plot['SortYear'],
        y=df_plot['Male'],
        name='Male Literacy',
        marker_color='#1f77b4',
        text=[f'{x:.1f}%' for x in df_plot['Male']],
        textposition='auto'
    ))

    # Female Bar
    fig.add_trace(go.Bar(
        x=df_plot['SortYear'],
        y=df_plot['Female'],
        name='Female Literacy',
        marker_color='#e377c2', # Pink/Pinkish-Purple
        text=[f'{x:.1f}%' for x in df_plot['Female']],
        textposition='auto'
    ))

    fig.update_layout(
        title='<b>Literacy Rate Composition by Gender</b>',
        xaxis_title='Year',
        yaxis_title='Literacy Rate (%)',
        barmode='group', # Grouped bars to see the "Gap" clearly
        plot_bgcolor='white',
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=500
    )

    fig.show()

else:
    print("Error: Education data not found.")

In [ ]:
#Literacy Rate Composition by gender - Pie Chart

import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Education' in dataframes:
        df_temp = dataframes['Education']
        current_selection = tuple(df_temp['Year'].dropna().unique())

# --- 2. PREPARE DATA ---
if 'Education' in dataframes:
    df = dataframes['Education'].copy()

    # Year(0), Male(11), Female(12)
    df_gender = df.iloc[:, [0, 11, 12]].copy()
    df_gender.columns = ['Year', 'Male', 'Female']

    # Filter by selected Years
    df_filtered = df_gender[df_gender['Year'].isin(current_selection)].copy()

    # Convert to numeric
    df_filtered['Male'] = pd.to_numeric(df_filtered['Male'], errors='coerce')
    df_filtered['Female'] = pd.to_numeric(df_filtered['Female'], errors='coerce')

    # Calculate the overall average for the Pie slices
    avg_male = df_filtered['Male'].mean()
    avg_female = df_filtered['Female'].mean()

    # --- 3. PLOT PIE CHART ---
    fig = go.Figure(data=[go.Pie(
        labels=['Male Literacy', 'Female Literacy'],
        values=[avg_male, avg_female],
        hole=.3, # Makes it a Donut chart, common in modern Power BI
        marker_colors=['#1f77b4', '#e377c2'],
        textinfo='label+percent',
        insidetextorientation='radial'
    )])

    fig.update_layout(
        title='<b>Literacy Composition by Gender</b>',
        annotations=[dict(text='Avg %', x=0.5, y=0.5, font_size=20, showarrow=False)],
        height=500,
        legend=dict(orientation="h", yanchor="bottom", y=-0.1, xanchor="center", x=0.5)
    )

    fig.show()

else:
    print("Error: Education data not found.")

In [ ]:
#Tetanus Texoid Coverage - YOY Change Graph 01
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd

# --- 1. DATA PREPARATION ---
if 'Health' in dataframes:
    df = dataframes['Health'].copy()
    tt_col = next((col for col in df.columns if "TETANUS" in str(col).upper() and "T" in str(col).upper()), None)

    if tt_col:
        # Filter for National Overall
        df_tt = df[df.iloc[:, 1].astype(str).str.strip().str.upper() == 'OVERALL'].copy()
        df_tt['Rate'] = pd.to_numeric(df_tt[tt_col], errors='coerce')
        df_tt['SortYear'] = df_tt.iloc[:, 0].astype(str).str[:4].astype(int)
        df_tt = df_tt.sort_values('SortYear')

        # Calculate YoY Change (the bars)
        df_tt['YoY_Change'] = df_tt['Rate'].diff()

        # Filter by selected years
        current_selection = year_slicer_widget.value or tuple(df_tt.iloc[:, 0].unique())
        df_plot = df_tt[df_tt.iloc[:, 0].isin(current_selection)].dropna(subset=['YoY_Change']).copy()

        # --- 2. CREATE COMBO CHART ---
        fig = make_subplots(specs=[[{"secondary_y": True}]])

        # Add BARS: YoY Change (pp)
        fig.add_trace(
            go.Bar(
                x=df_plot.iloc[:, 0],
                y=df_plot['YoY_Change'],
                name='YoY Change (pp)',
                marker_color=['#dc3545' if x < 0 else '#28a745' for x in df_plot['YoY_Change']],
                opacity=0.7,
                text=[f"{x:+.1f}" for x in df_plot['YoY_Change']],
                textposition='outside'
            ),
            secondary_y=False,
        )

        # Add LINE: Actual Coverage Trend
        fig.add_trace(
            go.Scatter(
                x=df_plot.iloc[:, 0],
                y=df_plot['Rate'],
                name='Coverage Trend (%)',
                mode='lines+markers',
                line=dict(color='#fd7e14', width=4), # Orange trend line
                marker=dict(size=10, symbol='diamond')
            ),
            secondary_y=True,
        )

        # --- 3. STYLING & DETAILING ---
        fig.update_layout(
            title='<b>Tetanus Toxoid Coverage: Annual Change & Trends</b>',
            xaxis=dict(title='Report Year', showgrid=False),
            yaxis=dict(title='YoY Change (Percentage Points)', zeroline=True, zerolinecolor='black'),
            yaxis2=dict(title='Total Coverage Rate (%)', showgrid=False, range=[0, 100]),
            plot_bgcolor='white',
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
            height=600
        )

        fig.show()
    else:
        print("Tetanus column not found.")
else:
    print("Health data missing.")

In [ ]:
#Tetanus Texoid Coverage - YOY Change Graph 02

import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
# Uses the years selected in your slicer
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Health' in dataframes:
        df_temp = dataframes['Health']
        current_selection = tuple(df_temp['Year'].dropna().unique())

# --- 2. PREPARE DATA ---
if 'Health' in dataframes:
    df = dataframes['Health'].copy()

    # Identify the correct column for Tetanus Toxoid (Total)
    tt_col = next((col for col in df.columns if "TETANUS" in str(col).upper() and "T" in str(col).upper()), None)

    if tt_col:
        # Standardize: Year(0), Region(1), TT_Rate(tt_col)
        df_tt = df.iloc[:, [0, 1]].copy()
        df_tt['Rate'] = pd.to_numeric(df[tt_col], errors='coerce')
        df_tt.columns = ['Year', 'Region', 'Rate']

        # Filter for National Level ('OVERALL')
        df_tt = df_tt[df_tt['Region'].astype(str).str.strip().str.upper() == 'OVERALL'].copy()

        # Sort by Year to ensure the difference calculation is correct
        df_tt['SortYear'] = df_tt['Year'].astype(str).str[:4].astype(int)
        df_tt = df_tt.sort_values('SortYear')

        # --- 3. CALCULATE YoY CHANGE ---
        # Replicating: CurrentRate - PreviousRate
        df_tt['YoY_Change'] = df_tt['Rate'].diff()

        # Filter for selected years AFTER calculating the diff (so the first year still has a comparison)
        df_plot = df_tt[df_tt['Year'].isin(current_selection)].dropna(subset=['YoY_Change'])

        # --- 4. PLOT YoY CHANGE ---
        fig = go.Figure()

        # Adding Bars with Conditional Colors (Green = Improvement, Red = Decline)
        fig.add_trace(go.Bar(
            x=df_plot['Year'],
            y=df_plot['YoY_Change'],
            marker_color=['#2ca02c' if x >= 0 else '#d62728' for x in df_plot['YoY_Change']],
            text=[f'{x:+.1f} pp' for x in df_plot['YoY_Change']],
            textposition='auto',
            name='Annual Change'
        ))

        fig.update_layout(
            title='<b>Tetanus Toxoid Coverage: Annual Change</b><br><sup>Percentage Point Shift Year-over-Year</sup>',
            xaxis_title='Year',
            yaxis_title='Change (Percentage Points)',
            plot_bgcolor='white',
            height=500,
            # Draw a line at zero for clear visual distinction
            shapes=[dict(type='line', y0=0, y1=0, x0=-0.5, x1=len(df_plot)-0.5,
                         line=dict(color="black", width=2))]
        )

        fig.show()
    else:
        print("Error: Tetanus Toxoid column not found.")
else:
    print("Error: Health data not found.")

In [ ]:
#Page 03

# # Adult literacy, immunization home owners and avg national income function - Again

# --- KPI DEFINITION: Average National Income ---
def calculate_avg_national_income(df_economy, selected_years_tuple):
    """
    Calculates the Average National Income for the selected years.
    Logic: Average of 'Avg Income per HouseHold' where Region is 'Pakistan'.
    """

    # 1. Create a working copy
    df = df_economy.copy()

    # 2. Filter for National Level data (Region = "Pakistan")
    # We strip whitespace to be safe ('Pakistan ' -> 'Pakistan')
    df_national = df[df['Region'].astype(str).str.strip() == 'Pakistan'].copy()

    # 3. Clean the Data: Convert Income column to numeric
    # The column name is exactly 'Avg Income per HouseHold' as per your inspection
    col_name = 'Avg Income per HouseHold'
    df_national[col_name] = pd.to_numeric(df_national[col_name], errors='coerce')

    # 4. Apply the Dynamic Year Filter
    df_filtered = filter_by_selected_years(df_national, selected_years_tuple, year_col_name='Year')

    # 5. Calculate the KPI
    # Corresponds to: AVERAGE(Economy[Avg Income per HouseHold])
    kpi_value = df_filtered[col_name].mean()

    # 6. Display the Result
    if pd.isna(kpi_value):
        print(f"Avg National Income: No Data for {selected_years_tuple}")
    else:
        # We format with commas for currency (e.g., 7,167.00)
        print(f"Avg National Income: {kpi_value:,.2f}")

    return kpi_value

# --- LINKING TO DASHBOARD ---
def update_dashboard(selected_years):
    print(f"--- DASHBOARD UPDATE (Selected Range: {selected_years}) ---")

    # 1. Literacy KPI
    if 'Education' in dataframes:
        calculate_national_adult_literacy(dataframes['Education'], selected_years)

    # 2. Immunization KPI
    if 'Health' in dataframes:
        calculate_national_full_immunization(dataframes['Health'], selected_years)

    # 3. Home Ownership KPI
    if 'Household' in dataframes:
        calculate_home_ownership(dataframes['Household'], selected_years)

    # 4. Avg National Income KPI (New)
    if 'Economy' in dataframes:
        calculate_avg_national_income(dataframes['Economy'], selected_years)
    else:
        print("Error: 'Economy.xlsx' not loaded.")

# Re-display the master interactive block
output_display = widgets.interactive_output(update_dashboard, {'selected_years': year_slicer_widget})
display(output_display)


#Literacy Gender Gap


# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Education' in dataframes:
        df_temp = dataframes['Education']
        current_selection = tuple(df_temp['Year'].dropna().unique())

print(f"Calculating Average Gap for: {current_selection}")

# --- 2. CALCULATE VALUE ---
if 'Education' in dataframes:
    df = dataframes['Education'].copy()

    # Columns: Year(0), Region(1), Male(11), Total(13)
    # We verify these indices based on standard file layout
    df_gap = df.iloc[:, [0, 1, 11, 13]].copy()
    df_gap.columns = ['Year', 'Region', 'Male', 'Total']

    # Filter 1: National Level ('OVERALL')
    df_gap = df_gap[df_gap['Region'].astype(str).str.strip().str.upper() == 'OVERALL'].copy()

    # Filter 2: Selected Years
    df_filtered = df_gap[df_gap['Year'].isin(current_selection)].copy()

    # Convert to numeric
    df_filtered['Male'] = pd.to_numeric(df_filtered['Male'], errors='coerce')
    df_filtered['Total'] = pd.to_numeric(df_filtered['Total'], errors='coerce')

    # --- 3. COMPUTE AVERAGE GAP ---
    # Formula: Average(Male) - Average(Total)
    avg_male = df_filtered['Male'].mean()
    avg_total = df_filtered['Total'].mean()
    avg_gap = avg_male - avg_total

    # --- 4. DISPLAY RESULT ---
    print("\n" + "="*40)
    print(f"  LITERACY GENDER GAP (Average)")
    print("="*40)
    print(f"  Avg Male Rate:   {avg_male:.2f}%")
    print(f"  Avg Total Rate:  {avg_total:.2f}%")
    print("-" * 25)
    print(f"  GAP VALUE:       {avg_gap:.2f}%")
    print("="*40)

else:
    print("Error: Education.xlsx not loaded.")

Output()

Calculating Average Gap for: ('2001-2002', '2004-2005', '2005-2006', '2006-2007', '2007-2008', '2008-2009')

========================================
  LITERACY GENDER GAP (Average)
========================================
  Avg Male Rate:   63.20%
  Avg Total Rate:  50.00%
-------------------------
  GAP VALUE:       13.20%
========================================

In [ ]:
#Access to toilet function

import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Household' in dataframes:
        df_temp = dataframes['Household']
        # Year.1 is usually the column for the Toilet section in this dataset
        current_selection = tuple(df_temp['Year.1'].dropna().unique())

# --- 2. PREPARE DATA ---
if 'Household' in dataframes:
    df = dataframes['Household'].copy()

    # Based on the file structure:
    # Col 6: Year, Col 7: Source (Type of Toilet), Col 10: Percentage (Total)
    # Col 21 is usually the 'Region' for this specific section
    df_toilet = df.iloc[:, [6, 7, 10, 21]].copy()
    df_toilet.columns = ['Year', 'Source', 'Percentage', 'Region']

    # --- 3. APPLY DAX FILTERS ---
    # Filter 1: Source = "FLUSH" (Case insensitive)
    mask_flush = df_toilet['Source'].astype(str).str.strip().str.upper() == "FLUSH"

    # Filter 2: Region = "TOTAL" (National level)
    mask_total = df_toilet['Region'].astype(str).str.strip().str.upper() == "TOTAL"

    # Filter 3: Selected Years
    mask_years = df_toilet['Year'].isin(current_selection)

    df_filtered = df_toilet[mask_flush & mask_total & mask_years].copy()

    # Convert to numeric
    df_filtered['Percentage'] = pd.to_numeric(df_filtered['Percentage'], errors='coerce')

    # --- 4. CALCULATE AVERAGE ---
    flush_avg = df_filtered['Percentage'].mean()

    # --- 5. DISPLAY RESULT ---
    print("\n" + "="*45)
    print(f"  ACCESS TO FLUSH TOILET (National)")
    print("="*45)
    print(f"  Source Type:     FLUSH")
    print(f"  Region:          TOTAL (National)")
    print(f"  Selected Years:  {len(df_filtered)}")
    print("-" * 30)
    print(f"  AVERAGE ACCESS:  {flush_avg:.2f}%")
    print("="*45)

else:
    print("Error: Household data not found.")

=============================================
  ACCESS TO FLUSH TOILET (National)
=============================================
  Source Type:     FLUSH
  Region:          TOTAL (National)
  Selected Years:  2
------------------------------
  AVERAGE ACCESS:  58.50%
=============================================

In [ ]:
import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Employment' in dataframes:
        df_temp = dataframes['Employment']
        current_selection = tuple(df_temp['Year'].dropna().unique())

# --- 2. PREPARE DATA ---
if 'Employment' in dataframes:
    df = dataframes['Employment'].copy()
    df_shift = df.iloc[:, [0, 4, 5]].copy()
    df_shift.columns = ['Year', 'Agriculture', 'Non_Agriculture']
    df_shift['Year'] = df_shift['Year'].ffill()

    for col in ['Agriculture', 'Non_Agriculture']:
        df_shift[col] = pd.to_numeric(df_shift[col], errors='coerce')

    df_filtered = df_shift[df_shift['Year'].isin(current_selection)].copy()
    df_grouped = df_filtered.groupby('Year')[['Agriculture', 'Non_Agriculture']].mean().reset_index()
    df_grouped['SortYear'] = df_grouped['Year'].astype(str).str[:4].astype(int)
    df_plot = df_grouped.sort_values(by='SortYear')

# --- 3. PLOT CHART WITH DYNAMIC SCALING ---
    fig = go.Figure()

    # Agriculture Area (Amber/Orange)
    fig.add_trace(go.Scatter(
        x=df_plot['SortYear'],
        y=df_plot['Agriculture'],
        mode='lines+markers',
        name='% in Agriculture',
        line=dict(color='#E65100', width=3),
        marker=dict(size=8),
        fill='tozeroy',
        fillcolor='rgba(230, 81, 0, 0.35)',
        hovertemplate='<b>Year</b>: %{x}<br><b>Ag</b>: %{y:.2f}%<extra></extra>'
    ))

    # Non-Agriculture Area (Navy Blue)
    fig.add_trace(go.Scatter(
        x=df_plot['SortYear'],
        y=df_plot['Non_Agriculture'],
        mode='lines+markers',
        name='% in Non-Agriculture',
        line=dict(color='#1A237E', width=3),
        marker=dict(size=8),
        fill='tozeroy',
        fillcolor='rgba(26, 35, 126, 0.35)',
        hovertemplate='<b>Year</b>: %{x}<br><b>Non-Ag</b>: %{y:.2f}%<extra></extra>'
    ))

    # Calculate dynamic limits for "Enlarged" view
    all_values = pd.concat([df_plot['Agriculture'], df_plot['Non_Agriculture']])
    min_val = all_values.min()
    max_val = all_values.max()

    fig.update_layout(
        title='<b>Workforce Structural Shift (Enlarged Area View)</b>',
        xaxis_title='Year',
        yaxis_title='Percentage (%)',
        xaxis=dict(tickmode='auto', nticks=10, tickformat="d"),
        # DYNAMIC RANGE: Starts slightly below the lowest value and ends slightly above the highest
        yaxis=dict(
            gridcolor='lightgrey',
            range=[min_val * 0.9, max_val * 1.1]
        ),
        plot_bgcolor='white',
        hovermode="x unified",
        legend=dict(orientation="h", y=1.1, x=0.5, xanchor="center"),
        height=500
    )

    fig.show()

else:
    print("Error: Employment.xlsx not loaded.")

In [ ]:
# @title
#Inspection Code - non functional

# ================== ECONOMY DATA CONFIRMATION ==================

print("\n========== ECONOMY DATAFRAME CHECK ==========")

# 1. Check dataframe existence
print("Economy dataframe exists:", 'Economy' in dataframes)

if 'Economy' in dataframes:
    df_dbg = dataframes['Economy']

    # 2. Basic shape
    print("\nShape:", df_dbg.shape)

    # 3. Column names
    print("\nColumns:")
    for i, col in enumerate(df_dbg.columns):
        print(f"{i}: {col}")

    # 4. Identify auto-detected columns
    col_cons = next((c for c in df_dbg.columns if "CONSUMPTION" in str(c).upper()), None)
    col_inc  = next((c for c in df_dbg.columns if "INCOME" in str(c).upper()), None)
    col_sav  = next((c for c in df_dbg.columns if "SAVING" in str(c).upper()), None)

    print("\nAuto-detected columns:")
    print("Consumption column:", col_cons)
    print("Income column     :", col_inc)
    print("Savings column    :", col_sav)

    # 5. Preview detected columns
    if col_cons:
        print("\nConsumption sample:")
        print(df_dbg[[df_dbg.columns[0], col_cons]].head(10))

    if col_inc:
        print("\nIncome sample:")
        print(df_dbg[[df_dbg.columns[0], col_inc]].head(10))

    if col_sav:
        print("\nSavings sample:")
        print(df_dbg[[df_dbg.columns[0], col_sav]].head(10))

    # 6. Numeric conversion check
    df_num = df_dbg.copy()
    for c in [col_cons, col_inc, col_sav]:
        if c:
            df_num[c] = pd.to_numeric(df_num[c], errors='coerce')

    print("\nNaN count after numeric conversion:")
    if col_cons:
        print("Consumption NaNs:", df_num[col_cons].isna().sum())
    if col_inc:
        print("Income NaNs     :", df_num[col_inc].isna().sum())
    if col_sav:
        print("Savings NaNs    :", df_num[col_sav].isna().sum())

    # 7. Groupby check
    year_col = df_dbg.columns[0]
    df_grp = df_num.groupby(year_col).mean(numeric_only=True).reset_index()

    print("\nGrouped (Yearly mean) head:")
    print(df_grp.head())

    if col_cons:
        print("\nConsumption after groupby:")
        print(df_grp[[year_col, col_cons]])

    print("\n========== END CHECK ==========\n")

else:
    print("ERROR: Economy dataframe not found!")

========== ECONOMY DATAFRAME CHECK ==========
Economy dataframe exists: True

Shape: (27, 5)

Columns:
0: Year
1: Region
2: Avg Income per HouseHold
3: Avg Consumpiton per HouseHold
4: Total Saving Per Households(Avg)

Auto-detected columns:
Consumption column: None
Income column     : Avg Income per HouseHold
Savings column    : Total Saving Per Households(Avg)

Income sample:
        Year  Avg Income per HouseHold
0  2001-2002                      9904
1  2001-2002                      6031
2  2001-2002                      7167
3  2004-2005                     13371
4  2004-2005                      7929
5  2004-2005                      9685
6  2005-2006                     14968
7  2005-2006                     10929
8  2005-2006                     12326
9  2007-2008                     17970

Savings sample:
        Year  Total Saving Per Households(Avg)
0  2001-2002                               907
1  2001-2002                               265
2  2001-2002                               453
3  2004-2005                              1292
4  2004-2005                               217
5  2004-2005                               564
6  2005-2006                               971
7  2005-2006                              1984
8  2005-2006                              1743
9  2007-2008                              2369

NaN count after numeric conversion:
Income NaNs     : 0
Savings NaNs    : 0

Grouped (Yearly mean) head:
        Year  Avg Income per HouseHold  Avg Consumpiton per HouseHold  \
0  2001-2002               7700.666667                    7159.000000
1  2004-2005              10328.333333                    9637.333333
2  2005-2006              12741.000000                   11175.000000
3  2007-2008              15017.333333                   13129.666667
4  2010-2011              22720.666667                   20071.333333

   Total Saving Per Households(Avg)
0                        541.666667
1                        691.000000
2                       1566.000000
3                       1887.666667
4                       2649.333333

========== END CHECK ==========

In [ ]:
#Income vs Consumption Gap trend

import plotly.graph_objects as go
import pandas as pd
import numpy as np

# ---------- HELPER: ROBUST COLUMN FINDER ----------
def find_column(df, keywords, fallback_index):
    for col in df.columns:
        col_upper = str(col).upper()
        if any(k in col_upper for k in keywords):
            return col
    return df.columns[fallback_index]


# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Economy' in dataframes:
        df_temp = dataframes['Economy']
        current_selection = tuple(df_temp['Year'].dropna().unique())

# --- 2. PREPARE DATA ---
if 'Economy' in dataframes:
    df = dataframes['Economy'].copy()

    # ✅ Robust column detection (handles "Consumpiton" typo)
    col_cons = find_column(df, ["CONSUMPTION", "CONSUMP", "EXPEND"], 2)
    col_inc  = find_column(df, ["INCOME"], 3)
    col_sav  = find_column(df, ["SAVING"], 4)

    df_eco = df[[df.columns[0], col_cons, col_inc, col_sav]].copy()
    df_eco.columns = ['Year', 'Consumption', 'Income', 'Savings']

    # Clean and Filter
    for col in ['Consumption', 'Income', 'Savings']:
        df_eco[col] = pd.to_numeric(df_eco[col], errors='coerce')

    df_filtered = df_eco[df_eco['Year'].isin(current_selection)].copy()

    # Group for trend plotting (Yearly Averages)
    df_plot = df_filtered.groupby('Year').mean(numeric_only=True).reset_index()
    df_plot['SortYear'] = df_plot['Year'].astype(str).str[:4].astype(int)
    df_plot = df_plot.sort_values(by='SortYear')

    # --- SAFETY CHECK (prevents silent failure) ---
    if df_plot['Consumption'].isna().all():
        raise ValueError("Consumption column contains no numeric data after processing.")

    # --- 3. PLOT CHART WITH YEARLY LABELS ---
    fig = go.Figure()

    # Consumption Line (Deep Orange)
    fig.add_trace(go.Scatter(
        x=df_plot['Year'],
        y=df_plot['Consumption'],
        name='Avg Consumption',
        mode='lines+markers+text',
        line=dict(color='#E65100', width=4),
        marker=dict(size=10),
        text=[f'{x:,.0f}' for x in df_plot['Consumption']],
        textposition="top center",
        textfont=dict(color='#E65100', size=11),
        hovertemplate='Consumption: %{y:,.0f}'
    ))

    # Income Line (Royal Blue)
    fig.add_trace(go.Scatter(
        x=df_plot['Year'],
        y=df_plot['Income'],
        name='Avg Income',
        mode='lines+markers+text',
        line=dict(color='#0D47A1', width=4),
        marker=dict(size=8),
        text=[f'{x:,.0f}' for x in df_plot['Income']],
        textposition="bottom center",
        textfont=dict(color='#0D47A1', size=10),
        hovertemplate='Income: %{y:,.0f}'
    ))

    # Savings Line (Forest Green)
    fig.add_trace(go.Scatter(
        x=df_plot['Year'],
        y=df_plot['Savings'],
        name='Avg Savings',
        mode='lines+markers',
        line=dict(color='#2E7D32', width=3, dash='dash'),
        marker=dict(size=8),
        hovertemplate='Savings: %{y:,.0f}'
    ))

    # --- 4. DYNAMIC ENLARGED SCALING ---
    all_vals = pd.concat([
        df_plot['Income'],
        df_plot['Consumption'],
        df_plot['Savings']
    ])

    fig.update_layout(
        title='<b>Income vs. Consumption & Savings Trend</b>'
              '<br><span style="font-size:12px;">Yearly Average Value per Household</span>',
        xaxis_title='Year',
        yaxis_title='Amount (Rs.)',
        yaxis=dict(
            gridcolor='lightgrey',
            range=[all_vals.min() * 0.8, all_vals.max() * 1.2]
        ),
        plot_bgcolor='white',
        hovermode="x unified",
        legend=dict(orientation="h", y=1.1, x=0.5, xanchor="center"),
        height=600,
        margin=dict(t=120)
    )

    fig.show()

else:
    print("Error: Economy data missing.")

In [ ]:
# @title
#Inspection code - non functional

# --- RUN THIS TO FIND THE TENURE DATA ---
if 'Household' in dataframes:
    df = dataframes['Household']

    print("--- 1. FIRST 5 ROWS (TOP OF FILE) ---")
    display(df.head(5))

    print("\n--- 2. COLUMN LIST WITH INDICES ---")
    for i, col in enumerate(df.columns):
        print(f"Index {i}: {col}")

    print("\n--- 3. SEARCHING FOR 'TENURE' OR 'OWNER' RELATED ROWS ---")
    # This searches the whole sheet for the word 'Owner' to find the right section
    mask = df.apply(lambda x: x.astype(str).str.contains('Owner', case=False)).any(axis=1)
    if mask.any():
        display(df[mask].head(10))
    else:
        print("Could not find 'Owner' in the data. Printing a sample of middle columns:")
        display(df.iloc[:10, 10:20])
else:
    print("Error: 'Household' sheet not found in dataframes.")

--- 1. FIRST 5 ROWS (TOP OF FILE) ---

,Year,Source,MAIN SOURCE OF DRINKING WATER,Unnamed: 3,Unnamed: 4,Unnamed: 5,Year.1,Source.1,TYPE OF TOILET (% HOUSEHOLDS),Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Year.3,Region.1,Feul used Lighting,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,NaN,NaN,U,R,T,NaN,NaN,NaN,U,R,...,TOTAL,NaN,NaN,NaN,Electricity,Gas/Oil,Candle,Other,Solar Panel,TOTAL
1,1998-1999,PIPED WATER,55,12,26,NaN,1998-1999,FLUSH,88,22,...,100,NaN,2004-2005,Urban,96.4,3.41,0.08,0.1,NaN,100
2,1998-1999,HAND PUMP,18,53,43,NaN,1998-1999,NON-FLUSH,6,15,...,100,NaN,2004-2005,Rural,74.27,24.76,0.23,0.75,NaN,100
3,1998-1999,MOTOR PUMP,20,12,14,NaN,1998-1999,NO-TOILET,6,63,...,100,NaN,2004-2005,Total,83.85,15.52,0.16,0.47,NaN,100
4,1998-1999,DUG WELL,2,11,8,NaN,1998-1999,TOTAL,100,100,...,100,NaN,2006-2007,Urban,97.58,2.14,0.1,0.18,NaN,100

--- 2. COLUMN LIST WITH INDICES ---
Index 0: Year
Index 1: Source
Index 2: MAIN SOURCE OF DRINKING WATER
Index 3: Unnamed: 3
Index 4: Unnamed: 4
Index 5: Unnamed: 5
Index 6: Year.1
Index 7: Source.1
Index 8: TYPE OF TOILET (% HOUSEHOLDS)
Index 9: Unnamed: 9
Index 10: Unnamed: 10
Index 11: Unnamed: 11
Index 12: Year.2
Index 13: Region
Index 14:  DISTRIBUTIONS OF HOUSEHOLDS BY HOUSING TENURE
Index 15: Unnamed: 15
Index 16: Unnamed: 16
Index 17: Unnamed: 17
Index 18: Unnamed: 18
Index 19: Unnamed: 19
Index 20: Year.3
Index 21: Region.1
Index 22: Feul used Lighting
Index 23: Unnamed: 23
Index 24: Unnamed: 24
Index 25: Unnamed: 25
Index 26: Unnamed: 26
Index 27: Unnamed: 27

--- 3. SEARCHING FOR 'TENURE' OR 'OWNER' RELATED ROWS ---
Could not find 'Owner' in the data. Printing a sample of middle columns:

,Unnamed: 10,Unnamed: 11,Year.2,Region,DISTRIBUTIONS OF HOUSEHOLDS BY HOUSING TENURE,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,T,NaN,NaN,NaN,OWN,RENT,FREE,SUBSIDISED RENT,TOTAL,NaN
1,41,NaN,2004-2005,OVERALL,86.57,7,5.32,1.1,100,NaN
2,12,NaN,2004-2005,Punjab,87.32,6.57,5.15,0.95,100,NaN
3,46,NaN,2004-2005,Sindh,87.33,6.94,4.79,0.93,100,NaN
4,100,NaN,2004-2005,NWFP,83.69,8.22,6.66,1.43,100,NaN
5,45,NaN,2004-2005,Balochistan,90.53,4.57,3.62,1.28,100,NaN
6,12,NaN,2006-2007,OVERALL,85.88,7.04,6.12,0.96,100,NaN
7,43,NaN,2006-2007,Punjab,86.52,6.16,6.49,0.83,100,NaN
8,100,NaN,2006-2007,Sindh,83.93,9.43,5.27,1.37,100,NaN
9,54,NaN,2006-2007,NWFP,86.62,6.76,5.8,0.81,100,NaN

In [ ]:
#Household Tenure Composition
import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Household' in dataframes:
        df_temp = dataframes['Household']
        current_selection = tuple(df_temp['Year.2'].dropna().unique())

# --- 2. PREPARE DATA ---
if 'Household' in dataframes:
    df = dataframes['Household'].copy()

    # Extract the Tenure columns specifically (Indices 12 to 17)
    # 12: Year, 13: Region, 14: Owner, 15: Rent, 16: Free, 17: Subsidized
    df_tenure = df.iloc[:, [12, 13, 14, 15, 16, 17]].copy()
    df_tenure.columns = ['Year', 'Region', 'Owner', 'Rent', 'RentFree', 'Subsidized']

    # Clean the numeric data
    for col in ['Owner', 'Rent', 'RentFree', 'Subsidized']:
        df_tenure[col] = pd.to_numeric(df_tenure[col], errors='coerce')

    # Filter: National Level ('OVERALL') and Selected Years
    # Note: Using .str.contains to handle potential extra spaces in Excel
    df_filtered = df_tenure[
        (df_tenure['Region'].astype(str).str.contains('OVERALL', case=False, na=False)) &
        (df_tenure['Year'].isin(current_selection))
    ].copy()

    if not df_filtered.empty:
        # Aggregate the averages for the Donut Chart slices
        results = {
            'Owner': df_filtered['Owner'].mean(),
            'On Rent': df_filtered['Rent'].mean(),
            'Rent Free': df_filtered['RentFree'].mean(),
            'Subsidized': df_filtered['Subsidized'].mean()
        }

        # --- 3. PLOT DONUT CHART ---
        fig = go.Figure(data=[go.Pie(
            labels=list(results.keys()),
            values=list(results.values()),
            hole=.4,
            marker=dict(colors=['#0D47A1', '#E65100', '#2E7D32', '#7B1FA2']), # Blue, Orange, Green, Purple
            textinfo='percent+label',
            pull=[0.05, 0, 0, 0] # Slightly pop out the 'Owner' slice
        )])

        fig.update_layout(
            title='<b>National Household Tenure Composition</b>',
            annotations=[dict(text='Tenure', x=0.5, y=0.5, font_size=18, showarrow=False)],
            height=500,
            showlegend=True,
            legend=dict(orientation="h", yanchor="bottom", y=-0.1, xanchor="center", x=0.5)
        )

        fig.show()
    else:
        print("No data found for the selected Years and 'OVERALL' region.")
else:
    print("Error: 'Household' sheet not found.")

In [ ]:
# @title
#Inspection code - non functional

# --- CONFIRMATION CODE FOR EMPLOYMENT SHIFT ---
if 'Employment' in dataframes:
    df_emp = dataframes['Employment']

    print("--- 1. UNIQUE EMPLOYMENT TYPES ---")
    # Checking the column that contains 'Agriculture' or 'Unpaid'
    # Based on your DAX, we look at the column that holds these categories
    # Usually index 1 or 2
    type_col = df_emp.columns[1]
    print(f"Categories found: {df_emp[type_col].unique()}")

    print("\n--- 2. REGION LABELS (Urban/Rural) ---")
    # Usually index 0 or another categorical column
    # Let's see the first few rows to find the Urban/Rural labels
    display(df_emp.head(10))

    # Check if 'Agriculture' and 'Unpaid' exist in the data
    available_types = [str(x).strip() for x in df_emp[type_col].unique()]
    print(f"\nTarget 'Agriculture' exists: {'Agriculture' in available_types}")
    print(f"Target 'Unpaid' exists: {'Unpaid' in available_types}")
else:
    print("Error: 'Employment' sheet not found.")

--- 1. UNIQUE EMPLOYMENT TYPES ---
Categories found: [nan 'Urban' 'Rural' 'Pakistan']

--- 2. REGION LABELS (Urban/Rural) ---

,Year,Area,Employement,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,Total,Employer,Agriculture,Non-Agriculture,Unpaid,Employee
1,2001-2002,Urban,100,1.71,2.01,19.44,11.96,64.88
2,2001-2002,Rural,100,0.76,19.4,10.37,35.33,34.14
3,2001-2002,Pakistan,100,1.02,14.74,12.8,29.07,42.38
4,2004-2005,Urban,100,0.63,2.52,29.57,11.09,56.19
5,2004-2005,Rural,100,0.19,23.28,14.15,29.59,32.79
6,2004-2005,Pakistan,100,0.32,17.16,18.7,24.13,39.69
7,2005-2006,Urban,100,1.85,2.51,20.24,10.69,64.71
8,2005-2006,Rural,100,0.74,20.42,10.2,30.26,38.39
9,2005-2006,Pakistan,100,1.09,14.78,13.36,24.11,46.67

Target 'Agriculture' exists: False
Target 'Unpaid' exists: False

In [ ]:
#Vulnerable employement share - year by year

import plotly.graph_objects as go
import pandas as pd

# --- 1. GET SELECTION ---
current_selection = year_slicer_widget.value
if not current_selection:
    if 'Employment' in dataframes:
        df_temp = dataframes['Employment']
        current_selection = tuple(df_temp.iloc[:, 0].dropna().unique())

# --- 2. PREPARE DATA ---
if 'Employment' in dataframes:
    df = dataframes['Employment'].copy()

    # Mapping based on your inspection:
    # Index 0: Year, Index 1: Area (Urban/Rural),
    # Index 4: Agriculture, Index 6: Unpaid
    df_vuln = df.iloc[:, [0, 1, 4, 6]].copy()
    df_vuln.columns = ['Year', 'Area', 'Agriculture', 'Unpaid']

    # Clean Year and numeric data
    df_vuln['Year'] = df_vuln['Year'].ffill()
    for col in ['Agriculture', 'Unpaid']:
        df_vuln[col] = pd.to_numeric(df_vuln[col], errors='coerce')

    # REPLICATING DAX: Vulnerable % = Agriculture + Unpaid
    df_vuln['Vulnerable_Pct'] = df_vuln['Agriculture'] + df_vuln['Unpaid']

    # Filter for Urban/Rural only (excluding 'Pakistan' total)
    df_filtered = df_vuln[
        (df_vuln['Area'].isin(['Urban', 'Rural'])) &
        (df_vuln['Year'].isin(current_selection))
    ].copy()

    # Sort by Year
    df_filtered['SortYear'] = df_filtered['Year'].astype(str).str[:4].astype(int)
    df_plot = df_filtered.sort_values(['SortYear', 'Area'])

    # --- 3. PLOT URBAN VS RURAL VULNERABILITY ---
    fig = go.Figure()

    for area in ['Urban', 'Rural']:
        area_data = df_plot[df_plot['Area'] == area]

        color = '#0D47A1' if area == 'Urban' else '#E65100' # Blue for Urban, Orange for Rural

        fig.add_trace(go.Bar(
            x=area_data['Year'],
            y=area_data['Vulnerable_Pct'],
            name=f'{area} Vulnerable Employment',
            marker_color=color,
            text=[f'{x:.1f}%' for x in area_data['Vulnerable_Pct']],
            textposition='auto'
        ))

    fig.update_layout(
        title='<b>Vulnerable Employment Share: Urban vs. Rural</b><br><sup>Sum of Agriculture & Unpaid Workers</sup>',
        xaxis_title='Year',
        yaxis_title='Percentage (%)',
        yaxis=dict(range=[0, max(df_plot['Vulnerable_Pct']) * 1.2], gridcolor='lightgrey'),
        barmode='group',
        plot_bgcolor='white',
        legend=dict(orientation="h", y=1.1, x=0.5, xanchor="center"),
        height=500
    )

    fig.show()

    # Summary Statistics
    avg_urban = df_plot[df_plot['Area'] == 'Urban']['Vulnerable_Pct'].mean()
    avg_rural = df_plot[df_plot['Area'] == 'Rural']['Vulnerable_Pct'].mean()
    print(f"\nAverage Vulnerability Rate - Urban: {avg_urban:.2f}%")
    print(f"Average Vulnerability Rate - Rural: {avg_rural:.2f}%")

else:
    print("Error: Employment data not found.")

Average Vulnerability Rate - Urban: 13.59%
Average Vulnerability Rate - Rural: 52.76%

In [ ]:
#Vulnerable employment share and comparison with Pakistan overall - Average

import pandas as pd
import plotly.graph_objects as go

# ============================================================
# 1. GET YEAR SELECTION
# ============================================================
current_selection = year_slicer_widget.value

if not current_selection:
    if 'Employment' in dataframes:
        df_temp = dataframes['Employment']
        current_selection = tuple(df_temp.iloc[:, 0].dropna().unique())


# ============================================================
# 2. LOAD & PREPARE DATA
# ============================================================
if 'Employment' not in dataframes:
    print("Error: Employment data missing.")
else:
    df = dataframes['Employment'].copy()

    df_emp = df.iloc[:, [0, 1, 4, 5, 6]].copy()
    df_emp.columns = [
        'Year', 'Area',
        'Agriculture', 'NonAgriculture', 'Unpaid'
    ]

    # Clean Year and numeric data
    df_emp['Year'] = df_emp['Year'].ffill()
    for col in ['Agriculture', 'NonAgriculture', 'Unpaid']:
        df_emp[col] = (
            df_emp[col].astype(str)
            .str.replace(',', '', regex=False)
        )
        df_emp[col] = pd.to_numeric(df_emp[col], errors='coerce').fillna(0)

    # Business logic
    df_emp['Vulnerable Employment'] = (
        df_emp['Agriculture'] + df_emp['Unpaid']
    )
    df_emp['Formal Employment'] = df_emp['NonAgriculture']

    # ============================================================
    # 3. AGGREGATION
    # ============================================================

    # Urban & Rural (bars)
    df_ur = df_emp[
        (df_emp['Area'].isin(['Urban', 'Rural'])) &
        (df_emp['Year'].isin(current_selection))
    ]

    df_ur_avg = (
        df_ur.groupby('Area')[['Formal Employment', 'Vulnerable Employment']]
        .mean()
        .reset_index()
    )

    # Pakistan benchmark (single national average)
    df_pk = df_emp[
        (df_emp['Area'] == 'Pakistan') &
        (df_emp['Year'].isin(current_selection))
    ]

    pk_formal = df_pk['Formal Employment'].mean()
    pk_vulnerable = df_pk['Vulnerable Employment'].mean()

    # ============================================================
    # 4. PLOT
    # ============================================================

    fig = go.Figure()

    # Formal (bars)
    fig.add_bar(
        x=df_ur_avg['Area'],
        y=df_ur_avg['Formal Employment'],
        name='Formal Employment',
        marker_color='#0D47A1',
        text=[f'{v:.1f}%' for v in df_ur_avg['Formal Employment']],
        textposition='outside'
    )

    # Vulnerable (bars)
    fig.add_bar(
        x=df_ur_avg['Area'],
        y=df_ur_avg['Vulnerable Employment'],
        name='Vulnerable Employment',
        marker_color='#E65100',
        text=[f'{v:.1f}%' for v in df_ur_avg['Vulnerable Employment']],
        textposition='outside'
    )

    # Pakistan benchmark lines
    fig.add_hline(
        y=pk_formal,
        line_dash='dash',
        line_color='#0D47A1',
        annotation_text=f'Pakistan Formal ({pk_formal:.1f}%)',
        annotation_position='top left'
    )

    fig.add_hline(
        y=pk_vulnerable,
        line_dash='dash',
        line_color='#E65100',
        annotation_text=f'Pakistan Vulnerable ({pk_vulnerable:.1f}%)',
        annotation_position='bottom left'
    )

    ymax = max(
        df_ur_avg[['Formal Employment', 'Vulnerable Employment']].max().max(),
        pk_formal,
        pk_vulnerable
    )

    fig.update_layout(
        title='<b>Employment Structure: Urban & Rural vs Pakistan Benchmark</b>',
        xaxis_title='Region',
        yaxis_title='Average Share (%)',
        barmode='group',
        plot_bgcolor='white',
        yaxis=dict(
            gridcolor='lightgrey',
            range=[0, ymax * 1.3]
        ),
        legend=dict(
            orientation='h',
            y=1.12,
            x=0.5,
            xanchor='center'
        ),
        height=550
    )

    fig.show()

In [ ]:
# @title
#Inspection code - non functional

if 'Household' in dataframes:
    df = dataframes['Household']

    print("--- 1. TESTING ELECTRICITY (Indices 20-22) ---")
    # Checking Year.3, Region.1, and Electricity column
    display(df.iloc[:10, [20, 21, 22]])

    print("\n--- 2. TESTING TOILET (Indices 6-10) ---")
    # Checking Year.1, Source.1, and Total %
    display(df.iloc[:10, [6, 7, 10]])

    print("\n--- 3. TESTING WATER (Indices 0-3) ---")
    # Checking Year, Source, and Total %
    display(df.iloc[:10, [0, 1, 3]])
else:
    print("Household sheet not found.")

--- 1. TESTING ELECTRICITY (Indices 20-22) ---

      Year.3 Region.1 Feul used Lighting
0        NaN      NaN       Electricity
1  2004-2005   Urban                96.4
2  2004-2005    Rural              74.27
3  2004-2005    Total              83.85
4  2006-2007   Urban               97.58
5  2006-2007    Rural              80.82
6  2006-2007    Total              86.61
7  2008-2009   Urban               97.73
8  2008-2009    Rural               87.1
9  2008-2009    Total              90.73

--- 2. TESTING TOILET (Indices 6-10) ---

      Year.1   Source.1 Unnamed: 10
0        NaN        NaN           T
1  1998-1999      FLUSH          41
2  1998-1999  NON-FLUSH          12
3  1998-1999  NO-TOILET          46
4  1998-1999      TOTAL         100
5  2001-2002      FLUSH          45
6  2001-2002  NON-FLUSH          12
7  2001-2002  NO-TOILET          43
8  2001-2002      TOTAL         100
9  2004-2005      FLUSH          54

--- 3. TESTING WATER (Indices 0-3) ---

        Year       Source Unnamed: 3
0        NaN          NaN          R
1  1998-1999  PIPED WATER         12
2  1998-1999    HAND PUMP         53
3  1998-1999   MOTOR PUMP         12
4  1998-1999     DUG WELL         11
5  1998-1999        OTHER         13
6  1998-1999        TOTAL        100
7  2001-2002  PIPED WATER         10
8  2001-2002    HAND PUMP         56
9  2001-2002   MOTOR PUMP         14

In [ ]:
#Household access to core infrastructure

import plotly.graph_objects as go
import pandas as pd
import numpy as np

# --- 1. ROBUST STATISTICAL AVERAGE FUNCTION ---
def get_verified_avg(df, year_col_idx, label_col_idx, val_col_idx, target_label, selected_years):
    # Extract specific column slice
    temp_df = df.iloc[:, [year_col_idx, label_col_idx, val_col_idx]].copy()
    temp_df.columns = ['Year', 'Label', 'Value']

    # 1. Forward fill Years to fix merged Excel cells
    temp_df['Year'] = temp_df['Year'].ffill()

    # 2. Convert to numeric, turning strings/blanks into NaN
    temp_df['Value'] = pd.to_numeric(temp_df['Value'], errors='coerce')

    # 3. Apply Filters: Must match 'TOTAL' or specific category exactly
    # We use .str.contains to handle potential trailing spaces in Excel
    mask = (temp_df['Year'].isin(selected_years)) & \
           (temp_df['Label'].astype(str).str.contains(target_label, case=False, na=False))

    # 4. Statistical Mean: .mean() in pandas automatically ignores NaNs (matches Power BI)
    return temp_df[mask]['Value'].mean()

# --- 2. EXECUTION ---
if 'Household' in dataframes:
    df_raw = dataframes['Household']
    # Use your selected years from the slicer
    years = year_slicer_widget.value or ['2004-2005']

    # Calculate each pillar using the verified offsets from your diagnostic check
    # Electricity: Index 21 is Region, 22 is %
    elec_acc = get_verified_avg(df_raw, 20, 21, 22, 'TOTAL', years)

    # Flush Toilet: Index 7 is Source, 10 is %
    toilet_acc = get_verified_avg(df_raw, 6, 7, 10, 'FLUSH', years)

    # Tap Water: Index 1 is Source, 3 is % (Labels as 'PIPED WATER')
    water_acc = get_verified_avg(df_raw, 0, 1, 3, 'PIPED WATER', years)

    # --- 3. PLOT DONUT ---
    vals = [elec_acc, toilet_acc, water_acc]
    labels = ['Electricity', 'Flush Toilet', 'Tap Water']

    fig = go.Figure(data=[go.Pie(
        labels=labels, values=vals, hole=.5,
        marker=dict(colors=['#FFD600', '#1A237E', '#03A9F4']),
        textinfo='label+percent'
    )])

    fig.update_layout(
        title=f'<b>Core Infrastructure Access Portfolio</b><br>Average: {", ".join(years)}',
        annotations=[dict(text='Access', x=0.5, y=0.5, font_size=20, showarrow=False)],
        height=550,
        legend=dict(orientation="h", y=-0.1, x=0.5, xanchor="center")
    )
    fig.show()

    print(f"Verified Stats: Electricity: {elec_acc:.1f}% | Toilet: {toilet_acc:.1f}% | Water: {water_acc:.1f}%")

Verified Stats: Electricity: 85.2% | Toilet: 34.4% | Water: 17.3%

In [ ]:
#Extra KPIs

import plotly.graph_objects as go
import pandas as pd

# --- KPI 1: SAVINGS RATE TREND (Urban vs Rural) ---
if 'Economy' in dataframes:
    df_eco = dataframes['Economy'].copy()
    # Indices: 0:Year, 1:Region, 2:Avg Income, 4:Total Saving
    df_s = df_eco.iloc[:, [0, 1, 2, 4]].copy()
    df_s.columns = ['Year', 'Region', 'Income', 'Savings']

    df_s['Year'] = df_s['Year'].ffill()
    for col in ['Income', 'Savings']:
        df_s[col] = pd.to_numeric(df_s[col], errors='coerce')

    # Statistical Calculation
    df_s['Savings_Rate'] = (df_s['Savings'] / df_s['Income']) * 100
    df_plot = df_s[df_s['Region'].isin(['Urban', 'Rural'])].dropna()

    fig1 = go.Figure()
    colors = {'Urban': '#0D47A1', 'Rural': '#E65100'}
    for region in ['Urban', 'Rural']:
        data = df_plot[df_plot['Region'] == region].sort_values('Year')
        fig1.add_trace(go.Scatter(x=data['Year'], y=data['Savings_Rate'], name=f'{region} Savings Rate',
                                 mode='lines+markers', line=dict(color=colors[region], width=3)))

    fig1.update_layout(title='<b>Household Savings Rate (%) by Region</b>',
                      yaxis_title='Savings as % of Income', plot_bgcolor='white', height=450)
    fig1.show()

# --- KPI 2: URBAN-RURAL INCOME GAP RATIO ---
if 'Economy' in dataframes:
    df_gap = df_s[df_s['Region'].isin(['Urban', 'Rural'])].copy()
    pivot = df_gap.pivot(index='Year', columns='Region', values='Income')
    if 'Urban' in pivot.columns and 'Rural' in pivot.columns:
        pivot['Ratio'] = pivot['Urban'] / pivot['Rural']

        fig2 = go.Figure(go.Bar(x=pivot.index, y=pivot['Ratio'], marker_color='#455A64',
                               text=[f'{x:.2f}x' for x in pivot['Ratio']], textposition='outside'))
        fig2.update_layout(title='<b>Income Disparity Ratio (Urban/Rural)</b>',
                          yaxis_title='Ratio (Urban Income : 1 Rural Income)', plot_bgcolor='white', height=450)
        fig2.show()

# --- KPI 3: LIGHTING SOURCE TRANSITION ---
if 'Household' in dataframes:
    df_h = dataframes['Household'].copy()
    # Index 20 (Year), 21 (Region), 22 (Electricity %)
    df_light = df_h.iloc[:, [20, 21, 22]].copy()
    df_light.columns = ['Year', 'Region', 'Electricity']
    df_light['Year'] = df_light['Year'].ffill()
    df_light['Electricity'] = pd.to_numeric(df_light['Electricity'], errors='coerce')

    # Filter for National (Total) row
    df_nat = df_light[df_light['Region'].astype(str).str.upper().str.strip() == 'TOTAL'].dropna().sort_values('Year')
    df_nat['Other'] = 100 - df_nat['Electricity']

    fig3 = go.Figure()
    fig3.add_trace(go.Bar(x=df_nat['Year'], y=df_nat['Electricity'], name='Electricity', marker_color='#FFD600'))
    fig3.add_trace(go.Bar(x=df_nat['Year'], y=df_nat['Other'], name='Other Sources', marker_color='#BDBDBD'))

    fig3.update_layout(title='<b>National Energy Transition (Lighting)</b>', barmode='stack',
                      yaxis_title='Percentage Share (%)', plot_bgcolor='white', height=450)
    fig3.show()

In [ ]:
# @title
#Inspection code - non funcutional

# --- DIAGNOSTIC CODE FOR EDUCATION SHEET ---
if 'Education' in dataframes:
    df_edu = dataframes['Education']
    print(f"--- Education Sheet Structure ---")
    print(f"Total Columns: {len(df_edu.columns)}")
    print(f"Column Names:\n{df_edu.columns.tolist()}")

    print("\n--- First 10 Rows of Education Sheet ---")
    display(df_edu.head(10))

    # Check for Region labels to fix the filter error
    if len(df_edu.columns) > 1:
        print("\n--- Unique Values in Region/Area Column ---")
        print(df_edu.iloc[:, 1].unique())
else:
    print("Error: 'Education' sheet not found in the 'dataframes' dictionary.")

--- Education Sheet Structure ---
Total Columns: 14
Column Names:
['Year', 'Region', 'Government Enrollment Primary', 'Unnamed: 3', 'Unnamed: 4', 'MATRIC GER (CLASSES 9-10 age 13-14) ', 'Unnamed: 6', 'Unnamed: 7', 'LITERACY RATES (10 YRS AND OLDER)', 'Unnamed: 9', 'Unnamed: 10', 'Adult Literacy Rate', 'Unnamed: 12', 'Unnamed: 13']

--- First 10 Rows of Education Sheet ---

,Year,Region,Government Enrollment Primary,Unnamed: 3,Unnamed: 4,MATRIC GER (CLASSES 9-10 age 13-14),Unnamed: 6,Unnamed: 7,LITERACY RATES (10 YRS AND OLDER),Unnamed: 9,Unnamed: 10,Adult Literacy Rate,Unnamed: 12,Unnamed: 13
0,NaN,NaN,M,F,T,M,F,T,M,F,T,M,F,T
1,1998-1999,OVERALL,76,74,75,53,27,40,59,31,45,58,28,43
2,1998-1999,Punjab,71,69,70,47,27,37,57,34,46,57,30,43
3,1998-1999,Sindh,74,74,74,61,39,51,65,35,51,64,32,49
4,1998-1999,NWFP,85,86,85,58,13,36,56,20,37,54,15,34
5,1998-1999,Balochistan,95,96,95,65,12,41,54,16,36,51,10,32
6,2001-2002,OVERALL,75,73,74,55,30,42,58,32,45,57,29,43
7,2001-2002,Punjab,70,69,69,55,34,44,57,36,47,57,32,44
8,2001-2002,Sindh,80,75,78,52,30,42,60,31,46,60,29,45
9,2001-2002,NWFP,81,85,82,62,20,41,57,20,38,55,17,35

--- Unique Values in Region/Area Column ---
[nan 'OVERALL' 'Punjab' 'Sindh' 'NWFP' 'Balochistan' 'KPK']

In [ ]:
#SDG Focused Gender Literacy Gap chart

import plotly.graph_objects as go
import pandas as pd

if 'Education' in dataframes:
    df_edu = dataframes['Education'].copy()

    # 1. SLICE SPECIFICALLY FOR LITERACY (Indices 8, 9, 10 are M, F, T)
    # Col 0: Year, Col 1: Region, Col 8: Male Lit, Col 9: Female Lit
    df_lit = df_edu.iloc[:, [0, 1, 8, 9]].copy()
    df_lit.columns = ['Year', 'Region', 'Male_Lit', 'Female_Lit']

    # 2. CLEANING
    df_lit['Year'] = df_lit['Year'].ffill()
    df_lit['Male_Lit'] = pd.to_numeric(df_lit['Male_Lit'], errors='coerce')
    df_lit['Female_Lit'] = pd.to_numeric(df_lit['Female_Lit'], errors='coerce')

    # 3. STATISTICAL CALCULATION: The Gender Gap
    # Higher gap means higher inequality (SDG 5 & SDG 4)
    df_lit['Gender_Gap'] = df_lit['Male_Lit'] - df_lit['Female_Lit']

    # 4. FILTER FOR "OVERALL" (Your National Label)
    df_nat = df_lit[df_lit['Region'] == 'OVERALL'].dropna().sort_values('Year')

    # 5. PLOTTING
    fig = go.Figure()

    # Male Line
    fig.add_trace(go.Scatter(x=df_nat['Year'], y=df_nat['Male_Lit'], name='Male Literacy',
                             line=dict(color='#0D47A1', width=3)))

    # Female Line
    fig.add_trace(go.Scatter(x=df_nat['Year'], y=df_nat['Female_Lit'], name='Female Literacy',
                             line=dict(color='#C2185B', width=3)))

    # The Gap (Bar)
    fig.add_trace(go.Bar(x=df_nat['Year'], y=df_nat['Gender_Gap'], name='Gender Gap (Points)',
                         marker_color='rgba(158, 158, 158, 0.5)'))

    fig.update_layout(
        title='<b>SDG 4.6: Literacy Rate & Gender Gap</b><br><sup>National Trend (Population 10 Years & Older)</sup>',
        xaxis_title='Survey Period',
        yaxis_title='Literacy Rate (%)',
        plot_bgcolor='white',
        height=500,
        legend=dict(orientation="h", y=-0.2)
    )

    fig.show()
else:
    print("Education sheet not found.")

In [ ]:
#EXTRA KPIs - SDGs focused

import plotly.graph_objects as go
import pandas as pd

# --- SDG 6: REDUCING OPEN DEFECATION (Sanitation) ---
if 'Household' in dataframes:
    df_san = dataframes['Household'].copy()
    # Indices 6, 7, 10 mapped from your diagnostic output
    df_od = df_san.iloc[:, [6, 7, 10]].copy()
    df_od.columns = ['Year', 'Source', 'OD_Rate']
    df_od['Year'] = df_od['Year'].ffill()
    df_od['OD_Rate'] = pd.to_numeric(df_od['OD_Rate'], errors='coerce')

    # Filter for NO-TOILET and Pakistan/Total logic
    df_od_plot = df_od[df_od['Source'].astype(str).str.contains('NO-TOILET', case=False, na=False)].dropna().sort_values('Year')

    fig_sdg6 = go.Figure(go.Scatter(
        x=df_od_plot['Year'], y=df_od_plot['OD_Rate'],
        mode='lines+markers', line=dict(color='#E91E63', width=4),
        fill='tozeroy', name='Open Defecation Rate'
    ))
    fig_sdg6.update_layout(title='<b>SDG 6.2: Reduction in Open Defecation</b>', yaxis_title='Rate (%)', plot_bgcolor='white')
    fig_sdg6.show()


# --- SDG 7: ACCESS TO MODERN ENERGY ---
if 'Household' in dataframes:
      # Add this logic inside your SDG 7 block to ensure the Header row is ignored
    df_sdg7 = df_elec[
        (df_elec['Region'].astype(str).str.upper().str.strip() == 'TOTAL') &
        (df_elec['Electricity'].notnull())
    ].dropna().sort_values('Year')
    df_h = dataframes['Household'].copy()
    # Using your identified Indices: 20:Year, 21:Region, 22:Electricity %
    df_elec = df_h.iloc[:, [20, 21, 22]].copy()
    df_elec.columns = ['Year', 'Region', 'Electricity']
    df_elec['Year'] = df_elec['Year'].ffill()
    df_elec['Electricity'] = pd.to_numeric(df_elec['Electricity'], errors='coerce')

    df_sdg7 = df_elec[df_elec['Region'].astype(str).str.upper().str.strip() == 'TOTAL'].dropna().sort_values('Year')

    fig_sdg7 = go.Figure(go.Scatter(
        x=df_sdg7['Year'], y=df_sdg7['Electricity'],
        mode='lines+markers', line=dict(color='#FBC02D', width=4),
        name='Electricity Access'
    ))
    fig_sdg7.update_layout(title='<b>SDG 7.1: Universal Access to Electricity</b>', yaxis_title='Access (%)', plot_bgcolor='white')
    fig_sdg7.show()

In [ ]:
#Final notes

import plotly.graph_objects as go

# --- FINAL TOUCH: PROJECT SUMMARY & LIMITATIONS ---
def show_project_notes():
    fig = go.Figure()

    # Create a simple "Information Card" visual
    fig.add_annotation(
        text=(
            "<b>Project Methodology & Notes:</b><br>"
            "• <b>Data Source:</b> Pakistan Social and Living Standards Measurement (PSLM) Survey.<br>"
            "• <b>Electricity Access:</b> Represents 'Lighting Source'. Reliability and Load Shedding are not captured.<br>"
            "• <b>Employment:</b> 'Vulnerable' includes Agriculture and Unpaid workers, reflecting structural fragility.<br>"
            "• <b>SDG Indicators:</b> Mapped to UN Tiers. OOSC is calculated as the inverse of Net Enrollment.<br>"
            "• <b>Calculations:</b> All averages are National Weighted Means where 'Total' rows are available."
        ),
        align='left', showarrow=False, xref="paper", yref="paper", x=0, y=1,
        bordercolor="black", borderpad=10, bgcolor="#f9f9f9", font=dict(size=14)
    )

    fig.update_layout(xaxis=dict(visible=False), yaxis=dict(visible=False),
                      height=250, margin=dict(l=20, r=20, t=20, b=20))
    fig.show()

show_project_notes()

In [ ]:
print("All done, Best of Luck!")

All done, Best of Luck!